### ISSUE TITLE
NPC Spell Attacks Scaling on Int/Wis/Cha

### ISSUE THREAD

**Issue by gazoir** [jbhaywood/5e-statblock-importer#102]
Hello! I'm absolutely loving your 5e importer. I'm trying to get spell attacks to import properly and seem to be struggling with the syntax. Is it possible to specify which stat to use in the actions description? Right now this Eldritch Blast is importing with Dexterity set as the stat, and it would be amazing to be able to specify Charisma during the import if possible?

```
Actions
Eldritch Blast. Ranged Spell Attack: +5 to hit, reach 5 ft., one target. Hit: 12 (1d10 + 5) force damage. 
```
![image](https://github.com/jbhaywood/5e-statblock-importer/assets/32458763/aed9a3d7-cbc9-499c-90d5-7cd03f95b024)

I've tried changing to Melee Weapon Attack, Melee Spell Attack, and Ranged Weapon. 

Here's the full statblock in case it helps...

```
Moffich Brak
Medium Humanoid
Armor Class 16
Hit points 24
Speed 30 ft.
STR
DEX
CON
INT
WIS
CHA
8 (-1) 10 (+0) 12 (+1) 10 (+0) 12 (+1) 16 (+3)
Saving Throws Cha (+5) Wis (+3) Con (+3)
Damage Resistances None
Damage Immunities None
Condition Immunities None
Senses None
Languages Abyssal
Challenge 1
Actions
Eldritch Blast. Ranged Spell Attack: +5 to hit, range 60 ft., one target. Hit: 12 (1d10 + 5) force damage. 
Spellcasting. Moffich Brak is a 1st level spellcaster. Its spellcasting ability is Charisma (spell save DC 13, +5 to hit with spell attacks)			
```

Thanks!

**Comment by jbhaywood** [comment]
I have a vague memory of fixing this, but maybe not. Can you check again? If it's still not correct, I don't have much time these days to work on this, but I'm open to pull requests.

**Comment by Aioros** [comment]
I know this is a fairly old issue, but I wanted to leave a quick explanation. Having Eldritch Blast there in the Actions section, it will be treated as a regular action, not an "actual" spell. In a standard statblock, it would look like this:

```
Moffich Brak
Medium Humanoid
Armor Class 16
Hit points 24
Speed 30 ft.
STR
DEX
CON
INT
WIS
CHA
8 (-1) 10 (+0) 12 (+1) 10 (+0) 12 (+1) 16 (+3)
Saving Throws Cha (+5) Wis (+3) Con (+3)
Damage Resistances None
Damage Immunities None
Condition Immunities None
Senses None
Languages Abyssal
Challenge 1
Spellcasting. Moffich Brak is a 1st level spellcaster. Its spellcasting ability is Charisma (spell save DC 13, +5 to hit with spell attacks). Moffich Brak has the following wizard spells prepared:
Cantrips (at will): eldritch blast
```
