### ISSUE TITLE
Lich spellblock doesn't import properly unless it has an extra linebreak

### ISSUE THREAD

**Issue by danshapiro** [jbhaywood/5e-statblock-importer#104]
wotc-lich.js has this:
9th level (1 slot): power word kill
Turn Resistance. The lich has advantage on saving
throws against any effect that turns undead.

If you change it instead to this:
9th level (1 slot): power word kill
Turn Resistance. The lich has advantage on saving throws against any effect that turns undead.

then the 9th level spell (only) does not import properly. I've found many other statblocks (omitted for copyright reasons) that reproduce this problem: the last spell in the spellblock does not import, but it can be fixed by inserting a random break into the line immediately following the spell block.

**Comment by jbhaywood** [comment]
I don't have much time these days to work on this, but I'm open to pull requests.

**Comment by jbhaywood** [comment]
Should be fixed now thanks to @Aioros.
