### ISSUE TITLE
Ability names are not imported with the correct capitalisation, even when the source is correct

### ISSUE THREAD

**Issue by Kirsham** [jbhaywood/5e-statblock-importer#107]
Ability names (Features, Actions, Bonus Actions, Reactions, Legendary Actions) should be in title case to be consistent with core D&D formatting. However, the parser will use incorrect capitalisation, even when the originally pasted text is correct.

Examples include:
* Incorrectly capitalising minor words (e.g., the, of, or), for example "Freedom of Movement" is incorrectly formatted "Freedom Of Movement"
* Incorrectly not capitalising words following a hyphen (e.g., "Skull-Splitting Howl" is incorrectly formatted "Skull-splitting Howl"
* Incorrectly not capitalising the word following a /, e.g., "1/Day" and "1/Turn" are incorrectly formatted "1/day" and "1/turn".

The parser should be able to correctly apply title case. However, it's probably simpler and more prudent to have the parser trust trust that the source formatting is correct and use that, rather than trying to have the parser override the original formatting, After all, it does that for the rest of the descriptions.

**Comment by jbhaywood** [comment]
The change in capitalization is a side affect of how the parser works. It would take a decent amount of work to make it retain the original capitalization, which I don't have time for these days. That's aside from the fact that the original capitalization isn't always correct. For example, I've noticed that copying from a lot of Kobold Press PDFs results in upper and lower case being applied randomly, which would look even stranger in the final statblock.
