### ISSUE TITLE
Bonus Action, Reaction and Legendary Action recharge on 1d6 rolls are not imported correctly

### ISSUE THREAD

**Issue by Kirsham** [jbhaywood/5e-statblock-importer#108]
Any Bonus Action, Reaction or Legendary Action with the Recharge property will be imported with 1/1 charges, but does not have a threshold for recharging with a 1d6 die roll defined. Actions, however, are imported correctly.

![image](https://github.com/jbhaywood/5e-statblock-importer/assets/72575642/eb9c03dc-9acd-4182-a2b4-55fa0d411360)

The details page looks like this, the Action Recharge field at the bottom is not populated for non-Action entries.

![image](https://github.com/jbhaywood/5e-statblock-importer/assets/72575642/952584c0-1062-4be0-b530-ed75d3c52f65)

**Comment by jbhaywood** [comment]
I don't have much time these days to work on this, but I'm open to pull requests.

**Comment by Aioros** [comment]
Implemented in v1.90.1
