### ISSUE TITLE
Players can see the Statblock Importer button and also private folders from the Actors tab

### ISSUE THREAD

**Issue by abrueckn** [jbhaywood/5e-statblock-importer#109]
I can understand the usefulness of letting the players have access to the statblock importer, but when they do they are able to see the full list of folders from the Actors tab, which has spoilers! I don't see any way to disable this or customizer permissions. Am I missing something?

**Comment by jbhaywood** [comment]
You're not missing anything. Your best bet is to turn off the module and only activate it when you need to add monsters.

**Comment by abrueckn** [comment]
Understood, thank you.
