### ISSUE TITLE
Icon missing, unsupported core version for 12.324

### ISSUE THREAD

**Issue by BrutusDM** [jbhaywood/5e-statblock-importer#110]
As it says on the tin, icon no longer in actor tab, modules says no longer supported core version

**Comment by mcubas76** [comment]
Would love to see this mod on V12. It is super helpful. It's no rush, but I just wanted to know if you were planning on updating it for V12, so I can plan accordingly. Thanks!

**Comment by jbhaywood** [comment]
Fixed in v1.83.00.

**Comment by mcubas76** [comment]
Thanks
!
