### ISSUE TITLE
Speed dose not import in version 12 

### ISSUE THREAD

**Issue by mtryoutlander** [jbhaywood/5e-statblock-importer#111]
Try to import a couple diffrent times on foundry v12 build 325.
useing 5e statblock importer 1.83.00 
The speed is never imported

**Comment by MaxPat931** [comment]
Looks like these two `data`s need to be changed to `system`
https://github.com/jbhaywood/5e-statblock-importer/blob/88bd57c05e9fef4b92c34c8cd7543a1d597f8411/scripts/sbiActor.js#L445-L446

https://github.com/jbhaywood/5e-statblock-importer/blob/88bd57c05e9fef4b92c34c8cd7543a1d597f8411/scripts/sbiActor.js#L461-L463

**Comment by jbhaywood** [comment]
Fixed in v1.83.01.
