### ISSUE TITLE
Not importing spellcasting feature

### ISSUE THREAD

**Issue by ChobitsCrazy** [jbhaywood/5e-statblock-importer#113]
Hello this is a great mod and I appreciate the effort put in. I would like to make a request to have the spellcasting feature added to the statblock on the creature when importing. Currently it only adds the spells but it's a good reference to have the feature listed on the sheet as well.

Using the Acolyte as an example here is the imported screens:
![image](https://github.com/jbhaywood/5e-statblock-importer/assets/21301107/257e440f-362e-4c98-b22c-9042e2725534)
![image](https://github.com/jbhaywood/5e-statblock-importer/assets/21301107/8da5f1e8-7fe9-4af1-beea-e4500ad99b0b)

This is what I would expect to see:
![image](https://github.com/jbhaywood/5e-statblock-importer/assets/21301107/99557ebd-40da-4897-b42f-49ec993212c5)

**Comment by jbhaywood** [comment]
Thanks for the nice words, but I don't plan on adding new features to this module. I've moved on from Foundry myself so there's not much incentive for me to put time into it. I'm more than happy to take pull requests, or even have someone take it over though.

**Comment by Aioros** [comment]
Implemented in v1.90.1
