### ISSUE TITLE
No spells in the generated character

### ISSUE THREAD

**Issue by Arkemnos** [jbhaywood/5e-statblock-importer#114]
Here is the statblock I used :

Duchess Calinda Després

Medium humanoid (Human), Neutral Good
Armor Class: 18 (Chain Mail and Shield)
Hit Points: 65 (10d8+20)
Speed: 30 ft.
Abilities:

STR: 14 (+2)
DEX: 10 (+0)
CON: 14 (+2)
INT: 12 (+1)
WIS: 18 (+4)
CHA: 16 (+3)
Saving Throws: Wis +7, Cha +6
Skills: Medicine +7, Insight +7, Religion +4
Senses: Passive Perception 14
Languages: Common, Celestial
Challenge: 5 (1,800 XP)

Spellcasting: Calinda is a 10th-level spellcaster. Her spellcasting ability is Wisdom (spell save DC 15, +7 to hit with spell attacks). She has the following cleric spells prepared:

Cantrips (at will): Light, Sacred Flame, Thaumaturgy
1st level (4 slots): Bless, Cure Wounds, Guiding Bolt, Shield of Faith
2nd level (3 slots): Lesser Restoration, Spiritual Weapon
3rd level (3 slots): Daylight, Dispel Magic, Beacon of Hope
4th level (3 slots): Guardian of Faith, Banishment
5th level (1 slot): Flame Strike, Mass Cure Wounds
Channel Divinity (2/Short Rest):

Turn Undead: As an action, Calinda presents her holy symbol and speaks a prayer censuring the undead. Each undead that can see or hear her within 30 feet must make a Wisdom saving throw (DC 15). If the creature fails its saving throw, it is turned for 1 minute or until it takes any damage.
Radiance of the Dawn: As an action, Calinda can use Channel Divinity to dispel any magical darkness within 30 feet of her and deal radiant damage to all hostile creatures within that range. Each creature must make a Constitution saving throw (DC 15). A creature takes radiant damage equal to 2d10 + her cleric level on a failed saving throw, and half as much damage on a successful one.
Actions:

Mace: Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 2) bludgeoning damage.
Sacred Flame: Ranged Spell Attack: The target must succeed on a DC 15 Dexterity saving throw or take 14 (3d8) radiant damage.
Bonus Actions:

Spiritual Weapon: When Calinda casts Spiritual Weapon, she can make a melee spell attack against a creature within 5 feet of the weapon. On a hit, the target takes 9 (1d8 + 4) force damage.
Reactions:

Warding Flare (3/Day): When Calinda is attacked by a creature within 30 feet that she can see, she can use her reaction to impose disadvantage on the attack roll, causing light to flare before the attacker before it hits or misses. An attacker that can’t be blinded is immune to this feature.
Condition Immunities: None
Senses: Passive Perception 14
Languages: Common, Celestial

**Comment by ChobitsCrazy** [comment]
In a lot of the places on that statblock you are using a ":" instead of a "."

For the spell casting section you should have it as such:

Spellcasting. Calinda is a 10th-level spellcaster. Her spellcasting ability is Wisdom (spell save DC 15, +7 to hit with spell attacks). She has the following cleric spells prepared:

Cantrips (at will): Light, Sacred Flame, Thaumaturgy
1st level (4 slots): Bless, Cure Wounds, Guiding Bolt, Shield of Faith
2nd level (3 slots): Lesser Restoration, Spiritual Weapon
3rd level (3 slots): Daylight, Dispel Magic, Beacon of Hope
4th level (3 slots): Guardian of Faith, Banishment
5th level (1 slot): Flame Strike, Mass Cure Wounds

**Comment by Arkemnos** [comment]
Thx for the feedback. I ask chatGPT to generate the template for 5e Statblock importer and it worked perfectly well.

**Comment by jbhaywood** [comment]
That's pretty good for AI generated. The parser is pretty sensitive to punctuation, so it might be work even better to put in an official statblock and tell it to match the formatting of that one in the future.
