### ISSUE TITLE
5E Statblock Importer error

### ISSUE THREAD

**Issue by kae0813** [jbhaywood/5e-statblock-importer#115]
Having an issue with the statblock importer. It is the most up to date version, 1.83.00. I have the error line from the console and the statblock attempting to import

foundry.js:68326 5E STATBLOCK IMPORTER: An error has occured. Please report it using the module link so it can get fixed.

Popcorn
Small Fey, Neutral Good

Armor Class 15 (natural armor)
Hit Points 35 (5d8 + 10)
Speed 20 ft., fly 30 ft. Lil Wings go burrr

STR
15 (+2)
DEX
12 (+1)
CON
14 (+2)
INT
12 (+1)
WIS
12 (+1)
CHA
11 (+0)

Saving Throws STR +4, CON +4
Skills Athletics +5, Intimidation +2, Perception +3, Stealth +4, Survival +3
Damage Vulnerabilities Fire
Damage Resistances Bludgeoning, Piercing, and Slashing from Nonmagical Attacks
Damage Immunities Poison
Condition Immunities Charmed, Frightened, Poisoned
Senses Darkvision 60 ft., Passive Perception 13
Languages Common, Sylvan
Challenge 1/2 (100 XP)
Proficiency Bonus +2

Keen Senses. Popcorn has advantage on Wisdom (Perception) checks that rely on sight, and hearing.

Camouflage. While Standing still Popcorn is indistinguishable from a normal plant (DC 18 Nature check to tell otherwise.)

Magic Resistance. Popcorn has advantage on saving throws against spells and other magical effects.

Familiar. Popcorn can serve another creature as a familiar, forming a magic, telepathic bond with that willing companion. While the two are bonded, the companion can sense what Popcorn senses as long as they are within 1 mile of each other. While Popcorn is within 10 feet of its companion, the companion shares Popcorn's Magic Resistance trait. At any time and for any reason, Popcorn can end its service as a familiar, ending the telepathic bond.

Actions
Chomp. Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) piercing damage.

 

Reactions
Magic Channelling. Popcorn can expend their reaction to have the spell cast by the Companion to take place at their location, so long as the caster is within 100ft

**Comment by jbhaywood** [comment]
It seems to work for me. I'm using v12 of Foundry. Maybe that makes a difference?
![image](https://github.com/user-attachments/assets/847d1a72-0c73-45f6-b91a-16cff0f9c7fa)
