### ISSUE TITLE
"5E STATBLOCK IMPORTER: An error has occured. Please report it using the module link so it can get fixed."

### ISSUE THREAD

**Issue by HalcyonEir** [jbhaywood/5e-statblock-importer#116]
I am unable to import any statblocks at the moment; I am only receiving the error message stating "5E STATBLOCK IMPORTER: An error has occured. Please report it using the module link so it can get fixed."
It is currently updated to the most recent update.

**Comment by jbhaywood** [comment]
I need the text of the stat block you're trying to import. The ones I test with are working fine in v12 of Foundry.
