### ISSUE TITLE
Unable to import text.

### ISSUE THREAD

**Issue by Nucleartwister6** [jbhaywood/5e-statblock-importer#120]
The importer does not allow text to be pasted in the statblock text area. I have tried by disabling all modules, using different game instances, and rolling back the version of Foundry used without any success. Any thoughts?

Statblock being used is the default on the manifest URL.

**Comment by Aioros** [comment]
You are absolutely right, apologies, that was a specific issue with Firefox (which I assume you're using) that I didn't catch. If you update the module to v1.90.2 it should work again. Let me know if that's not the case.

**Comment by Nucleartwister6** [comment]
Fixed! Thank you.
