### ISSUE TITLE
Hello I am getting an error when attempting to import.

### ISSUE THREAD

**Issue by summorme** [jbhaywood/5e-statblock-importer#123]
I am on the lastest version of the module and foundry. Here is the text I tried below:

> Alyxian the Tormented
> Huge Aberration, Typically Lawful Evil
> Armor Class 21 (natural armor)
> Hit Points 312 (25d12 + 150)
> Speed 40 ft, swim 40 ft
> STR 21(+5) DEX 18(+4) CON 22(+6) INT 15(+2) WIS 16(+3) CHA 20(+5)
> Saving Throws Str +10, Con +11, Wis +8
> Skills Deception +10, Insight +8, Perception +8
> Damage Resistances bludgeoning, piercing, and slashing from nonmagical attacks
> Damage Immunities necrotic
> Condition Immunities charmed, exhaustion, frightened, paralyzed, petrified, stunned
> Senses Blindsight 120 ft, passive Perception 18
> Languages Celestial, Common, Elvish, Telepathy 120 ft
> Proficiency +5
> Challenge 14 (11,500 XP)
> TRAITS
> Apotheonic Rejuvenation.  When Alyxian drops to 0 hit points, his body dies and cracks open like a cocoon. Alyxian instantly emerges from the cocoon in his second form, Alyxian the Callous, in the space where his previous form died. His initiative count doesn’t change.
> Divinely Blessed.  Alyxian can’t be surprised and can’t be changed into another form against his will.
> Magic Resistance.  Alyxian has advantage on saving throws against spells and other magical effects.
> Whirlwind of Weapons.  A magical aura of weapons surrounds Alyxian in a 10 foot radius. A creature that starts it's turn in the aura must succeed on a DC 17 Dexterity saving throw or take 10 (3d6) slashing damage, taking half as much on a success.
> Legendary Resistance (2/Day).  If the alyxian the tormented fails a saving throw, he can choose to succeed instead.
> ACTIONS
> Multiattack.  Alyxian makes four Grasping Hand attacks, or two Grasping Hand attacks and a Barreling Charge.
> Grasping Hand.  _Melee Weapon Attack:_ +12 to hit, reach 5 ft., one target. _Hit:_ 12 (2d6 + 5) force damage, and if the target is a Medium or smaller creature, it is grappled (escape DC 15). Alyxian has six hands, each of which can grapple one target.
> Barreling Charge.  Alyxian moves up to his speed in a straight line. All creatures in his path must make a DC 17 Dexterity saving throw or take 14 (4d6) bludgeoning damage and be knocked prone, or half as much damage on a success.
> Void Eyes (Recharge 5–6).  Alyxian targets up to two creatures he can see within 120 feet of himself. Each target must make a DC 17 Constitution saving throw, taking 28 (8d6) necrotic damage on a failed save, or half as much damage on a successful one.
> LEGENDARY ACTIONS
> Attack.  Alyxian makes one Grasping Hand attack.
> Weapons of Yore (Costs 2 Actions).  Ancient weapons embedded in Alyxian’s hide detach from Alyxian and fly about in a 15-foot-radius sphere centered on a point Alyxian can see within 60 feet of himself. A creature takes 18 (4d8) slashing damage when it enters that area for the first time on a turn or starts its turn there. The effect lasts until the end of Alyxian’s next turn, when the weapons return to Alyxian and embed themselves in his hide once again (causing him no harm).
> Decrepit Battalion (Costs 2 Actions).  Alyxian summons the memory of soldiers that did not survive the battles of the calamity, summoning 2 (1d4) Sword Wraith Warriors within 120 feet.

> Alyxian the Callous
> Large Celestial, Typically Lawful Evil
> Armor Class 22 (plate)
> Hit Points 252 (24d10 + 120)
> Speed 30 ft, fly 90 ft
> STR 23(+6) DEX 18(+4) CON 21(+5) INT 15(+2) WIS 16(+3) CHA 20(+5)
> Saving Throws Str +11, Con +10, Wis +8
> Skills Deception +10, Insight +8, Perception +8
> Damage Resistances  bludgeoning, piercing, and slashing from nonmagical attacks, radiant
> Condition Immunities charmed, exhaustion, frightened, paralyzed, petrified, restrained, stunned
> Senses Blindsight 120 ft, passive Perception 18
> Languages Celestial, Common, Elvish, Telepathy 120 ft
> Proficiency +5
> Challenge 14 (11,500 XP)
> TRAITS
> Apotheonic Rejuvenation.  When the alyxian the callous drops to 0 hit points, his body dies and sheds its wings, and he rises to his feet in his third form, Alyxian the Dispossessed. His initiative count doesn’t change.
> Divinely Blessed.  Alyxian can’t be surprised and can’t be changed into another form against his will.
> Magic Resistance.  Alyxian has advantage on saving throws against spells and other magical effects.
> Legendary Resistance (2/Day).  If the alyxian the callous fails a saving throw, he can choose to succeed instead.
> ACTIONS
> Multiattack.  Alyxian makes three Radiant Spear attacks. He can replace one of these attacks with Blinding Teleport or Crescent Moon Sweep.
> Radiant Spear.  _Melee or Ranged Weapon Attack:_ +12 to hit, reach 5 ft. or range 120 ft., one target. _Hit:_ 15 (2d8 + 6) radiant damage.
> Crescent Moon Sweep.  Alyxian slashes out with a sweep of his spear. Each creature within 10 ft. of Alyxian must succeed on a DC 17 Dexterity saving throw or take 19 (3d8 + 6) slashing damage and be knocked prone. On a successful save, a creature takes half as much damage and isn’t knocked prone.
> Blinding Teleport.  Alyxian teleports, along with any equipment he is wearing or carrying, to an unoccupied space he can see within 120 feet of himself. Each creature within 5 feet of his new location must succeed on a DC 17 Constitution saving throw or be blinded until the end of its next turn.
> Heavenly Destruction (1/Day).  Alyxian releases divine energy in a 90-foot cone. Each creature of his choice in that area must make a DC 17 Constitution saving throw. On a failed saving throw, the creature takes 31 (7d8) radiant damage and is knocked prone. On a successful save, a creature takes half as much damage and isn’t knocked prone.
> REACTIONS
> Reprimand.  When a creature Alyxian can see within 60 feet of him regains hit points, Alyxian reduces the number of hit points regained to 0, and he regains 22 (5d8) hit points instead.
> LEGENDARY ACTIONS
> Attack.  Alyxian makes one Radiant Spear attack.
> Celestial Chains.  Alyxian targets one creature he can see within 120 feet of himself. The target must succeed on a DC 17 Strength saving throw or be restrained by magical chains for 1 minute. While restrained in this way, the target can’t leave the space by any means. A creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.
> Flare (Costs 2 Actions).  Alyxian targets one creature he can see within 30 feet of himself. Light flares around the target, dealing 17 (5d6) radiant damage to it and half as much to any creatures within 10 feet of it.
> Halo of the Three (Costs 3 Actions).  Alyxian creates three 20ft radius rings that must touch, that appear to pulse with radiant yellow light. Any creature in these rings when Alyxian starts his turn must succeed on a DC 17 Constitution saving throw or take 45 (10d8) radiant damage as they detonate.

**Comment by summorme** [comment]
Update: had to manually install previous version to 1.83.03 from the upgraded. I was able to import without issue.

**Comment by Aioros** [comment]
Hi, I'll reopen this issue since it's definitely something that needs to be fixed. Do you mind letting me know what browser you're using, and maybe also where the statblock has been copied from? I was unable to reproduce the issue by copying the text from here.

**Comment by summorme** [comment]
Recreated the error by updating the module to the latest again. I am in Opera GX browser. I copied it from monstershuffler. Here is some pictures.
![image](https://github.com/user-attachments/assets/8a210f69-ae04-460a-8f2e-a5c3bd58316c)
![image](https://github.com/user-attachments/assets/60e3df26-0b12-4008-8b68-6ed5fb19b3a1)

**Comment by Aioros** [comment]
Do you mind trying the latest unstable version? You would need to install it by pasting this manifest URL: https://github.com/Aioros/5e-statblock-importer/releases/download/v1.90.6-3-g98df27a/module.json.

Apart from a few minor changes, it should give a little more information in the console about the error that I would like to see. Appreciate the help in any case, thank you.

**Comment by summorme** [comment]
Here you go, sorry I was busy this weekend. 
![image](https://github.com/user-attachments/assets/a878e096-bc0c-4268-b6d4-cda9bfcc0d5a)

**Comment by Aioros** [comment]
Well, I would like to abuse your patience a little bit and ask you to try this other version in the same way: https://github.com/Aioros/5e-statblock-importer/releases/download/v1.90.6-4-g391a5b2/module.json

If you do, this time you should see another line (or two) in the console right before the error, saying "5e Statblock Importer | DEBUG INFO: expand this:". If you could expand it and paste it here, I'd love to see that log.
Thanks again for your help.

**Comment by Aioros** [comment]
Actually, the latest version (v1.90.7) should fix this. Try it out and let me know. And thanks again for the help.

**Comment by summorme** [comment]
Checked with your most updated version, no errors!
