### ISSUE TITLE
Spellcasting Issue

### ISSUE THREAD

**Issue by GabeAntics** [jbhaywood/5e-statblock-importer#126]
The spellcasting portion doesn't seem to work. Can you help me out oplea

`Fairy Knight
Small Fey, Any Alignment

Armor Class 18 (studded leather, shield)
Hit Points 52 (8d6 + 24)
Speed 30 ft., fly 30ft.

STR
DEX
CON
INT
WIS
CHA
16 (+3)
18 (+4)
17 (+3)
12 (+1)
14 (+2)
16 (+3)

Saving Throws Con +6, Cha +6
Skills Athletics +6, Perception +5, Intimidation +6
Senses passive Perception 15
Languages Sylvan, 2 other languages
Challenge 4 (1,100 XP)	            	   Proficiency bonus +3

Brave. The fairy has advantage on saving throws against being frightened.
Fairy Wings. The fairy can’t use its fly speed while wearing medium or heavy armor.
Flying Charge. If the fairy is flying and dives at least 20 feet straight toward a target and then hits it with a spear attack, the attack deals an extra 7 (2d6) piercing damage to the target.
Actions
Multiattack. The fairy knight makes two attacks.
Spear. Melee Weapon Attack: +6 to hit, reach 5ft., one target. Hit: 6 (1d6 + 3) piercing damage plus 7 (2d6) force damage.
Shortbow. Ranged Weapon Attack: +7 to hit, range 80/320ft., one target. Hit: 7 (1d6 + 4) piercing damage.
Spellcasting. The fairy casts the druidcraft, faerie fire or enlarge/reduce spells, using Charisma as its spellcasting ability (spell save DC 14). Once it has cast faerie fire or enlarge/reduce, it can’t cast that spell again before finishing a long rest.
Bonus Actions
Incite Ally. The knight targets one ally it can see within 30 feet of it. If the target can see and hear the knight, the target can make one weapon attack as a reaction.
Reactions
Block. The fairy adds 3 to its AC against one attack that would hit it. To do so, it must see the attacker and be wielding a shield. If the attack is melee, the fairy can use a melee weapon instead of a shield.`

**Comment by Bleys74** [comment]
Having the same issues. Can't import spellcasters from an app that I'm using.

Gromgaard
Medium humanoid (halfling), neutral good
Armor Class 12 (natural armor)
Hit Points 22 (5d8)
Speed 25 ft.
STR DEX CON INT WIS CHA
16 (+3) 12 (+1) 18 (+4) 10 (+0) 14 (+2) 10 (+0)
Saving Throws CON +6, WIS +4
Skills Athletics +5, Religion +2
Damage Resistances None
Damage Immunities None
Condition Immunities None
Senses Darkvision 60 ft., passive Perception 12
Languages Common, Celestial
Challenge 1 (200 XP)
Divine Inspiration. Whenever Gromgaard makes a Wisdom saving throw or ability check, he can add his proficiency bonus to the roll, provided he isn't incapacitated.
Strong Body. Gromgaard has advantage on Strength checks and saving throws.
Spellcasting. Gromgaard is a 5th-level spellcaster. His spellcasting ability is Wisdom (spell save DC 12, +4 to hit with spell attacks). He can cast the following spells: At will: guidance, sacred flame. 1/day each: bless, shield of faith.
Actions
Divine Slam. Melee Attack: +3 to hit, reaching out with a powerful blow, dealing 9 (2d6 + 2) bludgeoning damage. On a hit, the target must succeed on a DC 12 Strength saving throw or be knocked prone.
Holy Strike. Melee Attack: +3 to hit, delivering a radiant-charged punch that deals 7 (2d4 + 2) radiant damage. Upon being hit, the target must succeed on a DC 10 Constitution saving throw or be blinded until the end of its next turn.

**Comment by Aioros** [comment]
Alright, sorry for the late reply, let me clarify. There are two main ways to include "Spellcasting" in a 5e statblock. The classic way is _outside_ the Actions, uses spell slots, and it looks roughly like this:

```
Spellcasting. The <monster name> is a <n>th-level spellcaster. His spellcasting ability is <ability> (spell save DC <dc>). He can cast the following spells: 
Cantrips (at will): <cantrip1>, <cantrip2>
1st level (<n> slots): <spell1>, <spell2>
...
```

The second, most recent way is _inside_ the Actions block, uses the innate spellcasting system of uses per day, and it looks like this:

```
Spellcasting. The <monster name> casts one of the following spells, using <ability> as the spellcasting ability (spell save DC <dc>):
At will: <spell 1>, <spell 2>, <spell 3>
3/day each: <spell 4>, <spell 5>
1/day: <spell 6>
```

Now, the fixes. @Kaallis, for the Fairy Knight, you probably want your Spellcasting line (inside the Actions) to be:

```
Spellcasting. The Fairy Knight casts one of the following spells, using Charisma as the spellcasting ability (spell save DC 14):
At will: druidcraft
1/day: fairie fire, enlarge/reduce
```

@Bleys74, for Gromgaard, if you want to keep the at-will-1/day structure, you'll need to move the Spellcasting in the Actions and change it slightly, so the end of your whole statblock would look like:

```
Actions
Divine Slam. Melee Attack: +3 to hit, reaching out with a powerful blow, dealing 9 (2d6 + 2) bludgeoning damage. On a hit, the target must succeed on a DC 12 Strength saving throw or be knocked prone.
Holy Strike. Melee Attack: +3 to hit, delivering a radiant-charged punch that deals 7 (2d4 + 2) radiant damage. Upon being hit, the target must succeed on a DC 10 Constitution saving throw or be blinded until the end of its next turn.
Spellcasting. Gromgaard casts one of the following spells, using Wisdom as the spellcasting ability (spell save DC 12):
At will: guidance, sacred flame
1/day: bless, shield of faith
```

Let me know if you have any issues with the changes.

**Comment by GabeAntics** [comment]
Thank you so much!
Having this template is really useful. Is there a full template that we can use?

**Comment by Aioros** [comment]
Not really, or at least none that I know of. The module is basically trying to accept any format that appeared in official WotC content for dnd5e. Providing a fillable template would probably be a little out of scope for what is supposed to be an importing tool.

What I definitely plan to add is better feedback, though. When some part of the block is wrong, it should give some useful information about what part it was, and ideally how to correct it... but I can't make promises on when that will happen.

**Comment by GabeAntics** [comment]
That's an amazing idea!

**Comment by Bleys74** [comment]
Thank you for your help!
