### ISSUE TITLE
Hit Points

### ISSUE THREAD

**Issue by Vethian** [jbhaywood/5e-statblock-importer#127]
Whenever I import now (it was working last week), the hit points are always 0/0.  I created a new world with only this module active and it still doesn't set the HP.

**Comment by Aioros** [comment]
Hey, thanks for the report. Can I ask which version of the dnd5e system you're on, and ideally one of the statblocks that you are trying to import?

**Comment by Vethian** [comment]
I had a colon after "Hit Points".  So, the input looked like this:
Armor Class: 10
Hit Points: 18 (4d8)
Speed: 30 ft.

Once I removed the colon it imported fine.
