### ISSUE TITLE
Attacks with Attack actions and Saves are broken

### ISSUE THREAD

**Issue by BrokenGojo** [jbhaywood/5e-statblock-importer#129]
![imagen_2024-11-07_021441598](https://github.com/user-attachments/assets/437ae0ec-bf41-46bf-955d-462b8ea70570)
_"Mind Burst. Ranged Spell Attack: +8 to hit, range 60 ft., one target. Hit: 21 (4d8 + 3) psychic damage, and the target must succeed on a DC 16 Intelligence saving throw or be unable to take reactions until the end of its next turn."_

I tried importing a hb monster with this attack and its import part of the stat block. After i tried with another stat block it happend again and after i delete the part where says _"DC 16 Inteligence saving throw"_ it works again with everything in the stat block.

**Comment by Aioros** [comment]
Hi, could you provide the full text that you are trying to import?

**Comment by BrokenGojo** [comment]
Hi, i did last time in Italic, but if u want the full stat block there it is:

Armarouge

Medium Monstrosity, Lawful Neutral

Armor Class 20 (natural armor, shield)
Hit Points 160 (21d8 + 63)
Speed 30 ft.

STR 18 (+4) | DEX 16 (+3) | CON 17 (+3) | INT 14 (+2) | WIS 15 (+2) | CHA 14 (+2)

Saving Throws Str +8, Con +7, Wis +6
Skills Athletics +8, Arcana +6, Insight +6, Intimidation +6
Damage Resistances fire, psychic
Damage Immunities radiant
Condition Immunities charmed, frightened
Senses darkvision 60 ft., passive Perception 12
Languages understands Common and Celestial but does not speak
Challenge 12 (8,400 XP)
Proficiency Bonus +4

Flame Armor. When a creature within 5 feet hits Armarouge with a melee attack, it takes 5 (1d10) fire damage.

Psionic Aura. Armarouge has advantage on saving throws against being stunned or paralyzed, as its mind is fortified by psychic energy.

Radiant Shield. As a bonus action, Armarouge can create a radiant barrier around itself, gaining temporary hit points equal to 15 (3d8 + 3). While the barrier remains, it reflects 5 radiant damage back at any attacker that hits Armarouge with a melee attack.

Actions
Multiattack. Armarouge makes two attacks with its Fire Lance or one attack with Fire Lance and one with Mind Burst.

Fire Lance. Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 15 (2d8 + 4) fire damage.

Mind Burst. Ranged Spell Attack: +8 to hit, range 60 ft., one target. Hit: 21 (4d8 + 3) psychic damage, and the target must succeed on a DC 16 Intelligence saving throw or be unable to take reactions until the end of its next turn.

Armor Cannon (Recharge 5–6). Armarouge fires a blast of condensed fire and psychic energy in a 30-foot line that is 5 feet wide. Each creature in that line must make a DC 17 Dexterity saving throw, taking 54 (12d8) fire and radiant damage on a failed save, or half as much damage on a successful one.

Reactions
Psychic Parry. Armarouge can add +4 to its AC against one ranged attack that would hit it, provided it can see the attacker.

Legendary Actions
Armarouge can take 2 legendary actions, choosing from the options below. It can only take one legendary action at a time and only at the end of another creature’s turn.

    Move. Armarouge moves up to its speed without provoking opportunity attacks.
    Fire Lance. Armarouge makes one Fire Lance attack.
    Radiant Pulse (Costs 2 Actions). Armarouge emits a burst of radiant energy in a 10-foot radius. Each creature in the area must make a DC 16 Constitution saving throw, taking 22 (5d8) radiant damage on a failed save, or half as much damage on a successful one.

**Comment by Aioros** [comment]
Thanks, it should be fixed now in v1.91.2. Let me know if you still have issues after updating the module.
