### ISSUE TITLE
RPGTinker

### ISSUE THREAD

**Issue by meta5by5** [jbhaywood/5e-statblock-importer#14]
Any suggestions for importing NPCs generated from rpgtinker.com? A copy of the HTML creates this text below. It actually pulls in a lot, but not spells, and other content, like the Mace action doesn't parse well. Thoughts?
BTW, You're importer is awesome. I'm looking forward to finding a NPC generator that produces the right format.

Carvin : Acolyte
Male Lightfoot Halfling, any alignment
Armor Class: 17 (Half plate, Shield)

Hit Points: 45 (6d8 +18)

Speed: 25ft (7,5m / 5 sqr)

Proficiency: +3

STR

13 (+1)

DEX

11 (+0)

CON

16 (+3)

INT

8 (-1)

WIS

17 (+3)

CHA

12 (+1)

Skills: Religion +2 Insight +6

Challenge: 3 (700 XP) 

Actions
Mace. Melee Weapon Attack +4 to hit, reach 5 ft, one target. Hit: 4 (1d6 +1 ) bludgeoning damage.

Properties: WOLOLO!,

Spells
Spellcasting. the Acolyte is an 6th-level cleric. Its spellcasting ability is Wisdom (spell save DC 14, to hit with spell attacks +6)

Cantrips (at will): Chill Touch, Thorn Whip, Resistance, Spare the Dying,

1st level (4 slots): Detect Magic, Purify Food and Drink, Shield of Faith, Ray of Sickness, Bane, Divine Favor, Cure Wounds,

2nd level (3 slots): Find Traps, Continual Flame, Spike Growth,

3rd level (3 slots): Water Walk,

 Click here to see spells descriptions (external tool)

Special Abilities
Potion of Healing: The healer carries a potion of healing (2d4+2 healing as a action) and a Healer's Kit.
Chosen of Gods: Once per week, as an act of incredible courage the acolyte can sacrifice himself to protect other. The DM can roll a d20 and add acolyte CR to this roll. If the check gets 20 or more the acolyte can receive one of the random bonuses: Regain one spell slot of his greater slot available; Maximize the healing of a spell, grant one target resitance/advantage against the next damage/saving throw.
Racial Features
Ability Modifiers: +2 Dex, +1 Cha

Small Size: small creatures should use d6 for hit dices

Lucky: When you roll a 1 on an attack roll, ability check, or saving throw, you can reroll the die and must use the new roll.

Brave: You have advantage on saving throws against being frightened.

Halfling Nimbleness: You can move through the space of any creature that is of a size larger than yours.

Naturally Stealthy: You can attempt to hide even when you are obscured only by a creature that is at least one size larger than you.

Languages: speaks Common and Halfling

**Comment by meta5by5** [comment]
Agreed. In fact, I should send RPGTinker the request instead. I did some moving around and came up with a working format. Some of it was just location in the list. But removing the “:” was a big game changer. 

 

I wouldn’t have even mentioned it as it isn’t too hard to do manually. But since the WOTC format is the standard, and is perfect for Foundry (the best VTT ever!) and YOUR tool (the best for DDB!), it would be a good selling point. Especially since DDB is the backbone of their online presence.

 

Anyway, just wondered is all. If I hear back from RPGTinker, I’ll let you know. Your products would pair up pretty well.

 

Benjamin

Aka meta5by5

**Comment by jbhaywood** [comment]
I'm closing this because I'm just not going to get around to adding the specs here. It actually changes as I add support for things that fall outside of the normal statblock format, so it would be hard to keep it up to date. The best bet for anyone wanting to make sure this module can parse their statblock is to take a look as the 5e SRD and make sure it follows the ones in there.
