### ISSUE TITLE
Damage of attacks not set

### ISSUE THREAD

**Issue by shadydeath** [jbhaywood/5e-statblock-importer#17]
<html>
<head><style>

</style></head><body>

OdhinnLarge God, lawful honorable
--
STR26 (+8) | DEX22 (+6) | CON26 (+8) | INT28 (+9) | WIS30 (+10) | CHA26 (+8)
Armor Class 25Hit Points 450 (30d12 + 240)Speed 40 ft.
Saving Throws Str +16, Con +16, Wis +17, Cha +16Skills Intimidation +16, Perception +18Damage Immunities necrotic, poison; bludgeoning, piercing andslashing from non magical weaponsCondition Immunities charmed, exhaustion, frightened, paralyzed,poisonedDamage Resistances radiantSenses passive Perception 28, darkvision 120 ft., truesight 120 ft.Languages all, telepathy 120 ft.Challenge 26 (90.000 XP)
Divine Weapons. The weapon attacks of a Deity are magical.When the Deity hits with any weapon, the weapon deals an extra 12d8radiant damage (included in the attack).Supreme Knowledge. Odhinn is the keeper of ultimate knowledge andalways succeeds on Arcana, Asatru, History, Nature and Religion checks.Implacable. Odhinn’s attacks ignore immunity or resistance.Supreme Master of the Futhark Circle. Odhinn can magically create a runiccircle, etching it on the floor. As an action, he chooses a spot on the floorwithin 120 ft., creating a circle 30 ft. in diameter. To keep it active, he mustbe able to see the circle and use a bonus action every turn. When a creatureOdhinn can see attacks a target within the circle, he can roll a d12 andsubtract the result to that hit roll. Enemies within the Futhark Circle lose anydamage resistance. Odhinn is considered always within the Futhark Circle.Legendary Resistances (3/Day). If Odhinn fails a saving throw, it canchoose to succeed instead.Magic Resistance. Odhinn rolls saving throws against spells and magicaleffects with advantage.Innate Spellcasting. Odhinn’s spellcasting ability is Intelligence (savingthrow DC 26, +18 to hit). Odhinn can innately cast the following spells,without the need for components.At will: bless, circle of death, circle of power, clairvoyance, counterspell, detectmagic, detect thoughts, foresight, haste, heroes’ feast, magic circle, message,mind blank, sanctuary, slow, teleportation circle, thaumaturgy.3/day each: holy aura, time stop, true polymorph, zone of truth1/day: power word kill
ACTIONS
Multiattack. Odhinn makes three Gungnir attacks.The Spear Gungnir. Melee Weapon Attack: it automatically hits a creaturewithin reach and sight, reach 10 ft., one target. Hit: 25 (2d12 + 11)piercing damage plus 54 (12d8) radiant damage.Gungnir, thrown. Odhinn hurls Gungnir, all creatures in a straightline 120 ft. long and 5 ft. wide suffer 18 (1d12+11) piercing damageplus 27 (6d8) radiant damage. Gungnir returns to Odhinn’s hand at thebeginning of his next turn.
REACTIONS
The Allfather Gaze. If an attack hits Odhinn and he can see hisaggressor, it fails.
LEGENDARY ACTIONS
Odhinn can take 3 legendary actions, choosing from the options below.Only one legendary action option can be used at a time and only at theend of another creature’s turn. Odhinn regains spent legendary actions atthe start of their turn.Gungnir. Odhinn attacks once with the spear Gungnir.Runic Mark (3 actions). Odhinn magically etches a rune on a target hecan see within the Futhark Circle. That target must pass a DC 21 Wisdomsaving throw or suffer a condition at Odhinn’s choice among the following:blinded, deafened, paralyzed, petrified or poisoned. A spell like lesserrestoration is capable of removing such condition.Spell. Odhinn casts a known spell.

 
<br style=" font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; ">

</body>
</html>

If you need more info please let me know - tested with latest current release of Importer and Foundry, 5e 1.5.7

**Comment by jbhaywood** [comment]
Is this really what the statblock looks like? A lot of lines are running together with no spaces or new lines to separate the individual parts of it. The parser isn't going to be able to handle that.

**Comment by shadydeath** [comment]
Yea this ia the block copies right from the PDF it is in.
It does handle most fine but not all.

If there are changes i can do manually quite easily i don't mind doing those i just have no clue where to start with it.

**Comment by shadydeath** [comment]
![afbeelding](https://user-images.githubusercontent.com/705408/150084902-87bedfe5-77c3-4c3a-ae5e-558c5154c745.png)
Screenshot of the block for reference

**Comment by jbhaywood** [comment]
There must be some strange formatting within the PDF if that's how it pastes. But I've noticed that with other ones too, not that bad though. What you see isn't always what you get. Basically you want it to look like the version you see in the PDF. Here it is cleaned up version so you can see the difference. I mostly had to add a lot of returns and spaces.

```
OdhinnLarge God, lawful honorable
STR 26 (+8)
DEX 22 (+6)
CON 26 (+8)
INT 28 (+9)
WIS 30 (+10)
CHA 26 (+8)
Armor Class 25
Hit Points 450 (30d12 + 240)
Speed 40 ft.
Saving Throws Str +16, Con +16, Wis +17, Cha +16
Skills
Intimidation +16, Perception +18
Damage Immunities necrotic, poison; bludgeoning, piercing and slashing from non magical weapons
Condition Immunities charmed, exhaustion, frightened, paralyzed, poisoned
Damage Resistances radiant
Senses
passive Perception 28, darkvision 120 ft., truesight 120 ft.
Languages all, telepathy 120 ft.
Challenge 26 (90.000 XP)
Divine Weapons. The weapon attacks of a Deity are magical. When the Deity hits with any weapon, the weapon deals an extra 12d8radiant damage (included in the attack).
Supreme Knowledge. Odhinn is the keeper of ultimate knowledge and always succeeds on Arcana, Asatru, History, Nature and Religion checks.
Implacable. Odhinn’s attacks ignore immunity or resistance. Supreme Master of the Futhark Circle. Odhinn can magically create a runic circle, etching it on the floor. As an action, he chooses a spot on the floor within 120 ft., creating a circle 30 ft. in diameter. To keep it active, he must be able to see the circle and use a bonus action every turn. When a creature Odhinn can see attacks a target within the circle, he can roll a d12 and subtract the result to that hit roll. Enemies within the Futhark Circle lose any damage resistance. Odhinn is considered always within the Futhark Circle.
Legendary Resistances (3/Day). If Odhinn fails a saving throw, it can choose to succeed instead. 
Magic Resistance. Odhinn rolls saving throws against spells and magical effects with advantage.
Innate Spellcasting. Odhinn’s spellcasting ability is Intelligence (saving throw DC 26, +18 to hit). Odhinn can innately cast the following spells, without the need for components.
At will: bless, circle of death, circle of power, clairvoyance, counterspell, detectmagic, detect thoughts, foresight, haste, heroes’ feast, magic circle, message, mind blank, sanctuary, slow, teleportation circle, thaumaturgy.
3/day each: holy aura, time stop, true polymorph, zone of truth
1/day: power word kill
ACTIONS
Multiattack. Odhinn makes three Gungnir attacks. The Spear Gungnir. Melee Weapon Attack: it automatically hits a creature within reach and sight, reach 10 ft., one target. Hit: 25 (2d12 + 11)piercing damage plus 54 (12d8) radiant damage. 
Gungnir, thrown. Odhinn hurls Gungnir, all creatures in a straight line 120 ft. long and 5 ft. wide suffer 18 (1d12+11) piercing damage plus 27 (6d8) radiant damage. Gungnir returns to Odhinn’s hand at the beginning of his next turn.
REACTIONS
The Allfather Gaze. If an attack hits Odhinn and he can see his aggressor, it fails.
LEGENDARY ACTIONS
Odhinn can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature’s turn. Odhinn regains spent legendary actions at the start of their turn.
Gungnir. Odhinn attacks once with the spear Gungnir.
Runic Mark (3 actions). Odhinn magically etches a rune on a target he can see within the Futhark Circle. That target must pass a DC 21 Wisdom saving throw or suffer a condition at Odhinn’s choice among the following: blinded, deafened, paralyzed, petrified or poisoned. A spell like lesser restoration is capable of removing such condition.
Spell. Odhinn casts a known spell.
```
