### ISSUE TITLE
Damage Immunities not being detected if copied from D&D Beyond

### ISSUE THREAD

**Issue by PragmaticBeaver** [jbhaywood/5e-statblock-importer#18]
I just noticed, that the import of a monster with damage immunities from D&D Beyond not works as expected.
The immunities will be completely empty even though the monster has a immunity.

As an example, see the Elder Brain Dragon here: https://www.dndbeyond.com/monsters/elder-brain-dragon
Because of copyright issues, I won't be able to paste the statblock into this Issue, hope the link is enough.

**Comment by jbhaywood** [comment]
Fixed in v1.2.9. Thanks for reporting it.
