### ISSUE TITLE
Statblock doesn't import attributes

### ISSUE THREAD

**Issue by Briqckoleur** [jbhaywood/5e-statblock-importer#2]
I tried to import the pasted statblock from DNDBeyond and it successfully imported the name and hp, but not attributes or ability names. Thank you!
Swarm of Rot Grubs
Medium swarm of Tiny beasts , unaligned

Armor Class 8
Hit Points 22 (5d8)
Speed 5 ft., climb 5 ft.

STR
2 (-4)
DEX
7 (-2)
CON
10 (+0)
INT
1 (-5)
WIS
2 (-4)
CHA
1 (-5)

Damage Resistances Piercing, Slashing
Condition Immunities Charmed, Frightened, Grappled, Paralyzed, Petrified, Prone, Restrained
Senses Blindsight 10 ft., Passive Perception 6
Languages --
Challenge 1/2 (100 XP)
Proficiency Bonus +2

Swarm. The swarm can occupy another creature’s space and vice versa, and the swarm can move through any opening large enough for a Tiny maggot. The swarm can’t regain hit points or gain temporary hit points.

Actions
Bites. Melee Weapon Attack: +0 to hit, reach 0 ft., one creature in the swarm’s space. Hit: The target is infested by 1d4 rot grubs. At the start of each of the target’s turns, the target takes 1d6 piercing damage per rot grub infesting it. Applying fire to the bite wound before the end of the target’s next turn deals 1 fire damage to the target and kills these rot grubs. After this time, these rot grubs are too far under the skin to be burned.

If a target infested by rot grubs ends its turn with 0 hit points, it dies as the rot grubs burrow into its heart and kill it. Any effect that cures disease kills all rot grubs infesting the target

**Comment by jbhaywood** [comment]
Should be fixed now. Thanks for reporting it.
