### ISSUE TITLE
Less spells imported in v1.4.0 as with the previous version

### ISSUE THREAD

**Issue by MartijnSanders** [jbhaywood/5e-statblock-importer#25]
Hi, just saw tonigth that the import of a character in v1.4.0 has about half of the spells as with the previous version (1.3.x). 
Will try to do a comparison come with a pinpoint of the reason

**Comment by jbhaywood** [comment]
That's not good. I did make some changes to how spells are parsed. If you could post an example of the statblock I can look into what's going on.

**Comment by MartijnSanders** [comment]
This is the grab from the pdf, some spurious spaces have already been removed:

Freja Owlsdaughter, the Shadowsworn
Medium humanoid (elf, shapechanger), neutral evil
Armor ClAss 16 (bracers of defense, mage armor)
Hit Points 123 (19d8 + 38)
sPeed 30 ft. (5 ft., fly 60 ft. in owl form)
str deX Con int Wis CHA
10 (+0) 15 (+2) 14 (+2) 12 (+1) 14 (+2) 18 (+4)
sAving tHroWs Dex +5, Wis +5, Cha +7
skills Arcana +4, Deception +7, Perception +5,
Persuasion +7, Stealth +5
senses darkvision 60 ft., passive Perception 15
lAnguAges Common, Elvish, Umbral
CHAllenge 7 (2,900 XP)
Fey Ancestry. Freja has advantage on saving throws
against being charmed, and magic can’t put her to
sleep.
Innate Spellcasting. Freja’s innate spellcasting ability
is Charisma. She can cast the following spell innately,
requiring no material components.
4/day: misty step (when in shadows, dim light, or
darkness only)
Shapechanger. Freja can use her action to polymorph
into an owl, or back into her humanoid form. Her
statistics, other than size, are the same in each form.
Any equipment she is wearing or carrying falls to the
ground, merges into her form, or is worn if the new form
is capable of wearing it. She reverts to her humanoid
form if she dies.
Spellcasting. Freja is a 10th-level spellcaster. Her
spellcasting ability is Charisma (spell save DC 15, +7 to
hit with spell attacks). She knows the following sorcerer
spells:
Cantrips (at will): blade ward, chill touch, friends, mage
hand, minor illusion, ray of frost
1st level (4 slots): mage armor, magic missile, shield
2nd level (3 slots): blindness/deafness, gust of wind
3rd level (3 slots): counterspell, hypnotic pattern
4th level (3 slots): blight, confusion
5th level (2 slots): cone of cold
Sunlight Sensitivity. While in sunlight, Freja has
disadvantage on attack rolls and on Wisdom (Perception)
checks that rely on sight.
Traveler in Darkness. Freja has advantage on Intelligence
(Arcana) checks made to know about shadow roads and
shadow magic spells or items.
ACTIONS
Rapier. Melee Weapon Attack: +5 to hit, reach 5 ft., one
target. Hit: 6 (1d8 + 2) piercing damage and 7 (2d6) cold
damage.

**Comment by MartijnSanders** [comment]
![afbeelding](https://user-images.githubusercontent.com/10100735/167630961-d7c5017e-9b0f-49ba-9d33-4102fca8f4dc.png)

**Comment by jbhaywood** [comment]
Is that from Courts of the Shadow Fey? I ran that myself.

Anyway, should be fixed now with release 1.4.1. It got confused by having both Innate Spellcasting and Spellcasting, usually it's just one or the other. This one exposed a few other issues as well, so I was able to get some other fixes in along with the spells.

**Comment by MartijnSanders** [comment]
Correct, i am in progress of setting up this adventure as it is not available for sale yet.
