### ISSUE TITLE
Anophiloi- Kobold Press Creature Codex

### ISSUE THREAD

**Issue by jlhess08** [jbhaywood/5e-statblock-importer#27]
ANOPHILOI
Small monstrosity, neutral
Armor Class 12
Hit Points 33 (6d6 + 12)
Speed 30 ft., climb 20 ft., fly 40 ft.
STR DEX CON INT WIS CHA
12 (+1) 14 (+2) 14 (+2) 5 (–3) 12 (+1) 6 (–2)
Skills Stealth +4
Damage Vulnerabilities cold
Damage Resistances poison
Condition Immunities poisoned
Senses darkvision 60 ft., passive Perception 11
Languages —
Challenge 1 (200 XP)
Blood Frenzy. The anophiloi has advantage on melee attack rolls
against any creature that doesn’t have all its hp.
Blood Sense. The anophiloi can pinpoint, by scent, the location
of living creatures within 30 feet of it.
Anophiloi
ACTIONS
Multiattack. The anophiloi makes two attacks: one with its claws
and one with its bite.
Bite. Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit:
5 (1d6 + 2) piercing damage, and if the target is Large or smaller,
the anophiloi attaches to it. While attached, the anophiloi
doesn’t attack. Instead, at the start of each of the anophiloi’s
turns, the target loses 5 (1d6 + 2) hp due to blood loss.
The anophiloi can detach itself by spending 5 feet of its
movement. It does so after it drains 20 hit points of blood from
the target or the target dies. A creature, including the target, can
use its action to detach the anophiloi by succeed on a DC 13
Strength check.
Claws. Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit:
4 (1d4 + 2) slashing damage.

**Comment by jbhaywood** [comment]
Can you describe what the problem is with this statblock?

**Comment by Oshcakes** [comment]
I see what the issue is but I am not sure how the module could solve for it. The monsters name shows up on its own line when you copy it from the pdf but its not in th text. Remove that line and it imports fine. Strange. 
![image](https://user-images.githubusercontent.com/61471647/173168866-51f5d719-77c6-406c-b59e-5d513c4183f1.png)

**Comment by jbhaywood** [comment]
Oh, yeah. If haven't seen that particular issue, but I have had to do a bit of cleanup on text copied from PDFs before. It's not ideal, but I can only make the computer so smart. :D And it still beats having to enter everything manually.
