### ISSUE TITLE
export too?

### ISSUE THREAD

**Issue by meta5by5** [jbhaywood/5e-statblock-importer#29]
Can you reverse theprocess to export an actor to a statblock, or even a csv?? Id pay $100 for that at the actor level or a compendium of actor entries. Lmk

**Comment by jbhaywood** [comment]
Do you mean just have it spit out a plain text statblock from the actor? Nothing fancy? And are you talking about NPC/monster statblocks, or player characters?

**Comment by jbhaywood** [comment]
I'm not sure exactly what you're looking for. If you can give me more details I'll reopen this, but I'm closing it for now.

**Comment by jbhaywood** [comment]
> Hiya James,The plain WotC monster/NPC statblock format. Something you could tweak and reupload if you wanted (using your tool, of course!)I dont know what the PC format would look like. Not sure anyone would use it unless it merged or was formatted into a character sheet. I just homebrew a ton of monsters to keep my players guessing and find that the FVTT is magical for tweaking stats and dropping spells and abilities together.>

It sounds like you want to export statblocks for monsters that only exist in Foundry? That you don't already have the text statblock for? If that's the case, I think that might infringe on their license and I wouldn't want this module to get banned or anything.

**Comment by meta5by5** [comment]
lol. This request was so long ago that I completely forgot about it. Since
existing monster statblocks already exist, there's no need for an export of
them. FVTT has the unique ability to build statblocks and create your own
NPCs. It is those that would be great to export. A disclaimer should be
good since most anything risks violation of WoTC/Hasbro's hold on stuff.
Even the statblock format itself.
