### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dallasrt** [jbhaywood/5e-statblock-importer#3]
I encountered an error. Here is the stat block:

Aboleth Overseer
Huge aberration, lawful evil
Armor Class 19 (natural armor)
Hit Points 273 (26d12 + 104)
Speed 10 ft., swim 40 ft.
STR DEX CON INT WIS CHA
 24 (+7) 9 (-1) 18 (+4) 20 (+5) 18 (+4) 18 (+4)
Saving Throws Con +11, Int +12, Wis +11
Skills Arcana +18, History +18, Perception +17
Senses darkvision 120 ft., passive Perception 27
Languages Deep Speech, telepathy 120 ft.
Challenge 21 (30,000 XP)
Amphibious. The aboleth can breathe air and water.
Legendary Resistance (3/Day). If the aboleth fails a saving throw, it
can choose to succeed instead.
Mucous Cloud. While underwater, the aboleth is surrounded by
transformative mucus. A creature that touches the aboleth or that
hits it with a melee attack while within 5 feet of it must succeed
on a DC 17 Constitution saving throw. On a failure, the creature
is diseased for 1d4 hours. The diseased creature can breathe only
underwater.
Probing Telepathy. If a creature communicates telepathically with
the aboleth, the aboleth learns the creature's greatest desires if the
aboleth can see the creature.
Innate Spellcasting (Psionics). The aboleth's innate spellcasting
ability is Intelligence (spell save DC 20). The aboleth can innately
cast the following spells, without providing material components:
At will: hypnotic pattern, invisibility, phantasmal force
3/day each: hallucinatory terrain, major image
2/day each: phantasmal killer, project image
1/day each: mirage arcane, psychic scream, weird, plane shift (self
only)
Actions
Multiattack. The aboleth makes four tentacle attacks.
Tentacle. Melee Weapon Attack: +14 to hit, reach 10 ft., one target.
Hit: 18 (2d10 + 7) bludgeoning damage and the target is grappled
(escape DC 18). If the target is a creature, it must succeed on a DC
19 Constitution saving throw or become diseased. The disease
has no effect for 1 minute and can be removed by any magic that
cures disease. After 1 minute, the diseased creature's skin becomes
translucent and slimy, the creature can't regain hit points unless it is
underwater, and the disease can be removed only by heal or another
disease-curing spell of 6th level or higher. When the creature is
outside a body of water, it takes 6 (1d12) acid damage every 10
minutes unless moisture is applied to the skin before 10 minutes
have passed.
Tail. Melee Weapon Attack: +14 to hit, reach 10 ft., one target.
Hit: 23 (3d10 + 7) bludgeoning damage.
Enslave (3/Day). The aboleth targets one creature it can see
within 30 feet of it. The target must succeed on a DC 19 Wisdom
saving throw or be magically charmed by the aboleth until the
aboleth dies or until it is on a different plane of existence from the
target. The charmed target is under the aboleth's control and can't
take reactions, and the aboleth and the target can communicate
telepathically with each other over any distance.
 Whenever the charmed target takes damage, the target can repeat
the saving throw. On a success, the effect ends. No more than once
every 24 hours, the target can also repeat the saving throw when it is
at least 1 mile away from the aboleth.
Fling. One Large or smaller object held or creature grappled by
the aboleth is thrown up to 60 feet and knocked prone. If a thrown
target strikes a solid surface, the target takes 3 (1d6) bludgeoning
damage for every 10 feet it was thrown. If the target is thrown at
another creature, that creature must succeed on a DC 18 Dexterity
saving throw or take the same damage and be knocked prone. If the
aboleth uses multiattack, it can use its Fling in place of one of its
tentacle attacks.
Legendary Actions
The aboleth can take 3 legendary actions, choosing from the options
below. Only one legendary action option can be used at a time and
only at the end of another creature's turn. The aboleth regains spent
legendary actions at the start of its turn.
Enslave. The aboleth uses its Enslave feature.
Tail Swipe. The aboleth makes one tail attack.
Psychic Drain (Costs 2 Actions). One creature charmed by the
aboleth takes 28 (8d6) psychic damage, and the aboleth regains
hit points equal to the damage the creature takes.
Cast a Spell (Costs 3 Actions). The aboleth casts a spell from its list
of innate spells, using a spell slot as normal.

**Comment by jbhaywood** [comment]
Should be fixed in version 1.0.9. Thanks for reporting it.
