### ISSUE TITLE
Parsing error when trying to add a "non-lawful" alignment

### ISSUE THREAD

**Issue by neunonics** [jbhaywood/5e-statblock-importer#30]
When trying to create an entry with an alignment of "any non-lawful alignment" the parser only captures "any non". This can be replicated in multiple ways by including the string "any non-whatever alignment" where "whatever" is your desired text. The exact string I used was "Medium humanoid (any race), any non-lawful alignment."

I am using Foundry VTT version 9 build 269 and 5e Statblock Importer v1.4.5

**Comment by jbhaywood** [comment]
Should be fixed with v1.5.0.
