### ISSUE TITLE
Getting Closer!

### ISSUE THREAD

**Issue by Greyhart42** [jbhaywood/5e-statblock-importer#33]
Most of the imports work fine. Randomly it seems, something doesn't import correctly.

For example, Goblin Assassin imports correctly:
![image](https://user-images.githubusercontent.com/47504205/184921103-59089c8d-7aca-4a71-9635-9d0f07b549ac.png)
 
Goblin Assassin
Small Humanoid (Goblin), Any Alignment
Armor Class 15 (studded leather armor)
Hit Points 16 (3d6 + 6)
Speed 30 ft., climb 20 ft.
STR DEX CON INT WIS CHA
8 (−1) 16 (+3) 14 (+2) 10 (+0) 10 (+0) 8 (−1)
Skills Stealth +7
Senses darkvision 60 ft., passive Perception 10
Languages Common, Goblin
Proficiency Bonus +2
Backstab. When the assassin has advantage on their attack roll
against a creature that isn’t a Construct or Undead, their attacks
deal an extra 1d6 damage and inflict a bleeding wound on the target
that lasts until the bleeding creature regains at least 1 hit point.
A bleeding creature loses 2 hit points for each bleeding wound
they have at the start of their turn. Any creature can use an action
to staunch all a target’s wounds, ending the effect.
Crafty. The assassin doesn’t provoke opportunity attacks when
they move out of an enemy’s reach.
ACTIONS
Scimitar. Melee Weapon Attack: +5 to hit, reach 5 ft., one target.
Hit: 6 (1d6 + 3) slashing damage.
Dagger. Melee or Ranged Weapon Attack: +5 to hit, reach 5 ft. or
range 20/60 ft., one target. Hit: 5 (1d4 + 3) piercing damage.
Summon Shadows (1/Day). A 10-foot-radius sphere of magical
darkness emanates from a point the assassin can see for 1 minute.
The assassin can see in this magical darkness. At the start of their
turn, the assassin can move the darkness up to 30 feet to a point
they can see. If the assassin takes damage, the effect ends.
BONUS ACTIONS
Sneak. The assassin takes the Hide action.

Goblin Minion lists Hit Points 6 Crafty under Features:

![image](https://user-images.githubusercontent.com/47504205/184921348-bdca3ac3-5a2a-4828-bace-d236d422d212.png)

Goblin Minion
Small Humanoid (Goblin), Any Alignment
Armor Class 14 (leather armor, shield)
Hit Points 6
Speed 30 ft., climb 20 ft.
STR DEX CON INT WIS CHA
8 (−1) 13 (+1) 10 (+0) 10 (+0) 8 (−1) 8 (−1)
Senses darkvision 60 ft., passive Perception 9
Languages Common, Goblin
Proficiency Bonus +2
Crafty. The minion doesn’t provoke opportunity attacks when they
move out of an enemy’s reach.
Minion. If the minion takes damage from an attack or as the result
of a failed saving throw, their hit points are reduced to 0. If the
minion takes damage from another effect, they die if the damage
equals or exceeds their hit point maximum, otherwise they take
no damage.
Tiny Stabs. If a visible enemy starts their turn within 5 feet of three
or more goblin minions, the enemy must succeed on a Dexterity
saving throw or take 1 piercing damage for each goblin minion
within 5 feet. The DC for this saving throw equals 10 + the number
of goblin minions within 5 feet of the enemy.
ACTIONS
Dagger (Group Attack). Melee or Ranged Weapon Attack: +3 to
hit, range 20/60 ft., one target. Hit: 1 piercing damage.

Goblin Cursespitter seems to be completely missing the To Me action:

![image](https://user-images.githubusercontent.com/47504205/184921733-26badcab-2c23-4dc9-88ae-1dfefafdbada.png)

Goblin Cursespitter
Small Humanoid (Goblin), Any Alignment
Armor Class 15 (leather armor, shield)
Hit Points 27 (5d6 + 10)
Speed 30 ft., climb 20 ft.
STR DEX CON INT WIS CHA
8 (−1) 14 (+2) 14 (+2) 10 (+0) 10 (+0) 15 (+2)
Saves Wis +2
Skills Stealth +4
Senses darkvision 60 ft., passive Perception 10
Languages Common, Goblin
Proficiency Bonus +2
Crafty. The cursespitter doesn’t provoke opportunity attacks when
they move out of an enemy’s reach.
ACTIONS
Toxic Touch. Melee or Ranged Spell Attack: +4 to hit, reach 5 ft.
or range 30 ft., one target. Hit: 7 (2d6) poison damage, and the
target must succeed on a DC 12 Constitution saving throw or be
poisoned for 1 minute (save ends at end of turn).
Brittle Bone Hex. The cursespitter chooses one creature they
can see within 60 feet of them. The target’s bones are wracked
with pain until the end of their next turn. The first time the target
willingly moves or uses an action, bonus action, or reaction before
then, they must succeed on a DC 12 Constitution saving throw or
take 9 (2d8) necrotic damage.
To Me! The cursespitter chooses up to two willing creatures they
can see within 30 feet of them. Each creature is teleported to an
unoccupied space within 5 feet of the cursespitter.
Dizzying Hex (2/Day). The cursespitter chooses one creature they
can see within 60 feet of them. The target must make a DC 12 Wisdom
saving throw. On a failed save, the target falls prone and can’t
stand back up for 1 minute (save ends at end of turn).
REACTIONS
Cowardly Commander. When a creature the cursespitter
can see hits them with an attack, the cursespitter chooses a willing
ally within 5 feet of them. The attack hits the ally instead.

Goblin Boss imported perfectly, as far as I can see:

![image](https://user-images.githubusercontent.com/47504205/184922108-9ecd5bea-ccf6-4135-bc29-db2e506e9fb1.png)

Goblin Boss
Small Humanoid (Goblin), Any Alignment
Armor Class 17 (studded leather armor, shield)
Hit Points 36 (8d6 + 8)
Speed 30 ft., climb 20 ft.
STR DEX CON INT WIS CHA
10 (+0) 16 (+3) 13 (+1) 12 (+1) 12 (+1) 10 (+0)
Saves Dex +5, Wis +3
Skills Insight +3, Intimidation +2, Stealth +5
Senses darkvision 60 ft., passive Perception 11
Languages Common, Goblin
Proficiency Bonus +2
Crafty. The boss doesn’t provoke opportunity attacks
when they move out of an enemy’s reach.
ACTIONS
Multiattack. The boss makes two Shortsword or Shortbow
attacks. They can use Command in place of one attack.
Shortsword. Melee Weapon Attack: +5 to hit, reach 5 ft.,
one target. Hit: 6 (1d6 + 3) piercing damage.
Shortbow. Ranged Weapon Attack: +5 to hit, range 80/320 ft.,
one target. Hit: 6 (1d6 + 3) piercing damage.
Command. The boss chooses one ally they can see within 30 feet
of them. If the target can hear the boss, the target can use their
reaction to move up to their speed or make one weapon attack.
BONUS ACTIONS
Get Reckless (Recharge 6). Each willing ally within 30 feet of the
boss that can hear them becomes reckless until the start of the
boss’s next turn. While reckless, a creature has advantage on attack
rolls, and attack rolls against the creature have advantage.
REACTIONS
Cowardly Commander. When a creature the boss
can see hits them with an attack, the boss chooses
a willing ally within 5 feet of them. The attack
hits the ally instead.

Those are the four I tested on.

Oh! How would I modify the Source parameter in the Importer? I'd like to just like to copy & paste the Source as Flee Mortals. I mean, I could just type it in to the character sheet, I suppose.

**Comment by jbhaywood** [comment]
These are fixed in 1.5.4. I had to add support for a couple more non-standard things MCDM is doing with their monsters. Why can't people just stick to the format? 😂

**Comment by Greyhart42** [comment]
Well, it’s a pre-release. That’s part of the problem.

Most everything is working. I’ve used it to import all the Goblins.

Ken
