### ISSUE TITLE
Issues Importing 

### ISSUE THREAD

**Issue by rprejean** [jbhaywood/5e-statblock-importer#34]
Found Monsterizer, by rpgbot.net, first and then they referenced your adon which is awesome. Unfortunately, I ran into a problem attempting to import the following homebrew creature generated on their site. 

`## Empress Giant Spider
*Large Beast , Chaotic Evil*
___

- **Armor Class** 19 (natural)
- **Hit Points** 383 59d10+59
- **Speed** 60 ft., Climb 60 ft.
- **Initiative** +5
___
|STR|DEX|CON|INT|WIS|CHA|
|:---:|:---:|:---:|:---:|:---:|:---:|
|18 (+4)|18 (+4)|18 (+4)|18 (+4)|18 (+4)|18 (+4)|
___
- **Saving Throws** Dex +11, Str +10
- **Skills** Acrobatics +11, Athletics +10, Stealth +11
- **Condition Immunities** blinded, charmed, deafened, frightened, poisoned
- **Damage Resistances** 
- **Damage Immunities** nonmagical bludgeoning, nonmagical piercing, nonmagical slashing
- **Senses** blindsight 10 ft., darkvision 60 ft.,  Passive Perception 10
- **Languages** --
- **Challenge** 20 **Proficiency Bonus** 6
___
***Spider Climb***. The Giant Spider can climb difficult surfaces, including upside down on
      ceilings, without needing to make an ability check.

***Web Sense***. While in contact with a web, the Giant Spider knows the exact location of any
      other creature in contact with the same web.

***Web Walker***. The Giant Spider ignores movement restrictions caused by webbing.
### Actions
***Bite***. Melee Weapon Attack: +11 to hit, reach 5 ft., one creature. Hit: 7 (6d8 + 3) piercing damage, and the target must make a DC 11 Constitution saving throw, taking 9 (2d8) poison damage on a failed save, or half as much damage on a successful one. If the poison damage reduces the target to 0 hit points, the target is stable but poisoned for 1 hour, even after regaining hit points, and is paralyzed while poisoned in this way.

***Web (Recharge 5–6)***. Ranged Weapon Attack: +5 to hit, range 30/60 ft., four creatures in a 10' diameter. Hit: The target is restrained by webbing. As an action, the restrained target can make a DC 12 Strength check, bursting the webbing on a success. The webbing can also be attacked and destroyed (AC 10; hp 5; vulnerability to fire damage; immunity to bludgeoning, poison, and psychic damage).

### Description
To snare its prey, a giant spider spins elaborate webs or shoots sticky strands of webbing from its abdomen. Giant spiders are most commonly found underground, making their lairs on ceilings or in dark, web-filled crevices. Such lairs are often festooned with web cocoons holding past victims.

*[Created in the Monsterizer](https://RPGBOT.net/dnd5/tools/monsterizer).*`

**Comment by rprejean** [comment]
It is due to all of the extra formattings they have in their stat block. I removed the extraneous markdown code and it imported fine. 

Empress Giant Spider
Large Beast, Chaotic Evil
Armor Class 19 (natural armor)
Hit Points 383 59d10+59
Speed 60 ft., Climb 60 ft.
Initiative +5
STR
DEX
CON
INT
WIS
CHA
18 (+4) 20 (+5) 12 (+1) 2 (-4) 11 (+0) 4 (-3)
Saving Throws Dex +11, Str +10
Skills Acrobatics +11, Athletics +10, Stealth +11
Condition Immunities blinded, charmed, deafened, frightened, poisoned
Damage Resistances 
Damage Immunities nonmagical bludgeoning, nonmagical piercing, nonmagical slashing
Senses blindsight 10 ft., darkvision 60 ft.,  Passive Perception 10
Languages --
Challenge 20 Proficiency Bonus 6
Spider Climb. The Giant Spider can climb difficult surfaces, including upside down on
ceilings, without needing to make an ability check.

Web Sense. While in contact with a web, the Giant Spider knows the exact location of any
other creature in contact with the same web.

Web Walker. The Giant Spider ignores movement restrictions caused by webbing.
Actions
Bite. Melee Weapon Attack: +11 to hit, reach 5 ft., one creature. Hit: 7 (6d8 + 3) piercing damage, and the target must make a DC 11 Constitution saving throw, taking 9 (2d8) poison damage on a failed save, or half as much damage on a successful one. If the poison damage reduces the target to 0 hit points, the target is stable but poisoned for 1 hour, even after regaining hit points, and is paralyzed while poisoned in this way.

Web (Recharge 5–6). Ranged Weapon Attack: +5 to hit, range 30/60 ft., four creatures in a 10' diameter. Hit: The target is restrained by webbing. As an action, the restrained target can make a DC 12 Strength check, bursting the webbing on a success. The webbing can also be attacked and destroyed (AC 10; hp 5; vulnerability to fire damage; immunity to bludgeoning, poison, and psychic damage).

Description
To snare its prey, a giant spider spins elaborate webs or shoots sticky strands of webbing from its abdomen. Giant spiders are most commonly found underground, making their lairs on ceilings or in dark, web-filled crevices. Such lairs are often festooned with web cocoons holding past victims.

**Comment by jbhaywood** [comment]
I was able to copy the text from this page and have it work...

![image](https://user-images.githubusercontent.com/5131886/188251455-53f54607-cd80-4f5c-a2fe-750b7552db25.png)

**Comment by jbhaywood** [comment]
It pasted like this...

```
Aboleth

Large Aberration, Lawful Evil
Armor Class 17 (natural)
Hit Points 135 (18d10+36)
Speed 10 ft., Swim 40 ft.
Initiative -1
STR	DEX	CON	INT	WIS	CHA
21 (+5)	9 (-1)	15  (+2)	18  (+4)	15 (+2)	18 (+4)
Saving Throws Con +6, Int +8, Wis +6
Skills History +8, Perception +6
Senses darkvision 120 ft., Passive Perception 16
Languages Deep Speech, telepathy 120 ft.
Challenge 10 (5900XP) Proficiency Bonus +4

Amphibious. The Aboleth can breathe air and water.

Mucuous Cloud. While underwater, the Aboleth is surrounded by transformative mucus. A creature that touches the Aboleth or that hits it with a melee attack while within 5 feet of it must make a DC 14 Constitution saving throw. On a failure, the creature is diseased for 1d4 hours. The diseased creature can breathe only underwater.

Probing Telepathy. If a creature communicates telepathically with the Aboleth, the Aboleth learns the creature's greatest desires if the Aboleth can see the creature.
Actions

Multiattack. The aboleth makes three tentacle attacks.

Enslave. (3/Day). The aboleth targets one creature it can see within 30 feet of it. The target must succeed on a DC 14 Wisdom saving throw or be magically charmed by the aboleth until the aboleth dies or until it is on a different plane of existence from the target. The charmed target is under the aboleth's control and can't take reactions, and the aboleth and the target can communicate telepathically with each other over any distance. Whenever the charmed target takes damage, the target can repeat the saving throw. On a success, the effect ends. No more than once every 24 hours, the target can also repeat the saving throw when it is at least 1 mile away from the aboleth.

Tail. Melee Weapon Attack: +9 to hit, reach 10 ft. one target. Hit: 15 (3d6 + 5) bludgeoning damage.

Tentacle.. Melee Weapon Attack: +9 to hit, reach 10 ft., one target. Hit: 12 (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased. The disease has no effect for 1 minute and can be removed by any magic that cures disease. After 1 minute, the diseased creature's skin becomes translucent and slimy, the creature can't regain hit points unless it is underwater, and the disease can be removed only by heal or another disease-curing spell of 6th level or higher. When the creature is outside a body of water, it takes 6 (1d12) acid damage every 10 minutes unless moisture is applied to the skin before 10 minutes have passed.
Legendary Actions

The Aboleth can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The Aboleth regains spent legendary actions at the start of its turn.

Detect. The aboleth makes a Wisdom (Perception) check.

Psychic (Costs 2 actions). Drain. One creature charmed by the aboleth takes 10 (3d6) psychic damage, and the aboleth regains hit points equal to the damage the creature takes.

Tail. Swipe. The aboleth makes one tail attack.
```

**Comment by jbhaywood** [comment]
Where did you copy the text from?

**Comment by rprejean** [comment]
It is from the sites NPC generator from a section that instructed that is to be used with your mod. 

I got it to work by removing all of the markup from their code.

**Comment by jbhaywood** [comment]
The module works with plain text, as you've figured out. If you copy from the "Stat Block" tab instead of "Export" it should work just fine. 

I think it's just a matter of that page not being very clear. The "Virtual Tabletops" section is separate from the other sections and you're not meant to use any of the text with markdown or JSON from that page. It says to use the stat block text, but the wording could be more clear that it means to go back to the previous tab.

![image](https://user-images.githubusercontent.com/5131886/188254262-974ee38a-843e-47b7-94dc-1d7fd22a4b8a.png)

**Comment by rprejean** [comment]
Thanks, James, I appreciate your time and nice app/mod.

Sincerely,
Robert Prejean
