### ISSUE TITLE
tetra-cube (statblock generator)

### ISSUE THREAD

**Issue by GuazP** [jbhaywood/5e-statblock-importer#35]
I'm not sure if it's possible to include such statblock generator with GM Binder/Markdown compatybility, but if you think it's worth to add, I believe adding such compatibility might add statblock importer flexibility :)

I'm not sure, but that's my first result for 'dnd 5e statblock generator' in google, so I assume it might be pretty popular.

**Comment by jbhaywood** [comment]
Are you saying that you want this module to support markdown? It doesn't need to. You just copy the plain text from the web page and paste it into the module window.

I just tried it with [D&D 5e Statblock Generator](https://tetra-cube.com/dnd/dnd-statblock.html) and it works fine.

**Comment by GuazP** [comment]
Hmmm... I tried this to before posting an issue, however, it seems like it does work actually... I had to mess something up when I tried before, now it works brilliant like from dndbeyond page. Sry for bother you, and thank you for awesome work!

**Comment by GuazP** [comment]
Ah i Found the culprit, not every mob imports, for example take Eater of Dust as example:

> Eater Of Dust (Yakat-Shi)
> Medium aberration, neutral evil
> Armor Class 17 (natural armor)
> Hit Points 114 (12d8 + 60)
> Speed 30 ft.
> STR
> 20 (+5)
> 
>  
> DEX
> 14 (+2)
> 
>  
> CON
> 20 (+5)
> 
>  
> INT
> 10 (+0)
> 
>  
> WIS
> 15 (+2)
> 
>  
> CHA
> 17 (+3)
> 
> Saving Throws Str +9, Con +9, Cha +7
> Skills Athletics +9, Perception +6
> Damage Resistances acid, cold
> Damage Immunities bludgeoning, piercing, poison and slashing from nonmagical attacks
> Condition Immunities blindness, lightning, poisoned
> Senses blindsight 60 ft., passive Perception 16
> Languages understands Abyssal, Common, Infernal, and Void Speech, telepathy 100 ft.
> Challenge 9 (5,000 XP)
> Innate Spellcasting. the eater of dust's innate spellcasting ability is Charisma (spell save DC 15, +7 to hit with spell attacks). It can innately cast the following spells, requiring no material components:
> 
> 3/day each: freedom of movement, inflict wounds, true strike
> 1/day each: cure wounds (as 3rd level), magic weapon (as 6th level), misty step
> Regeneration. The eater of dust regains 5 hit points at the start of its turn. If it takes fire damage, this trait does not function at the start of its next turn. The eater of dust dies only if it starts its turn with 0 hit points and does not regenerate.
> Unending Hunger. An eater of dust can devour any substance with its mawblade, regardless of composition, and never get full. It can even gain nourishment from eating dust or soil (hence the name given to the race by various fiends). If an eater of dust's mawblade is ever stolen, lost, or destroyed, it slowly starves to death.
> Weapon Bond. A mawblade is part of the eater of dust. It can strike any creature as if it were magically enchanted and made of silver, iron, or other materials required to overcome immunities or resistances. An eater of dust always knows the location of its mawblade as if using the locate creature spell.
> Actions
> Multiattack. The eater of dust makes two mawblade attacks, or makes one mawblade attack and casts inflict wounds.
> Mawblade. Melee Weapon Attack: +9 to hit, one target. Hit: 19 (4d6 + 5) piercing damage, and the target must make a successful DC 17 Constitution saving throw or gain one level of exhaustion.

It's taken from the same stat-generator :) 
https://tetra-cube.com/dnd/dnd-statblock.html

**Comment by jbhaywood** [comment]
Can you point out which part exactly isn't importing right? I just want to make sure I don't overlook it.

**Comment by jbhaywood** [comment]
I ran into an error with that statblock you posted and so updated the module with a fix. Let me know if it works for you now with v1.5.5.

**Comment by GuazP** [comment]
So far I've tried over 40 mobs, including my old saved ones... And didn't found any problem. Thank you :D.
