### ISSUE TITLE
Weapons are considered potions?

### ISSUE THREAD

**Issue by AlbanT** [jbhaywood/5e-statblock-importer#38]
I found this excellent addon very recently and tried to import an item today:
> Shatterspike
Weapon (longsword), uncommon (requires attunement)
>
>You have a +1 bonus to attack and damage rolls you make with this magic weapon. If it hits an object, the hit is automatically a critical hit, and it can deal bludgeoning or slashing damage to the object (your choice). Further, damage from nonmagical sources can’t harm the weapon.
>
>Proficiency with a longsword allows you to add your proficiency bonus to the attack roll for any attack you make with it.
>
>Notes: Bonus: Magic, Damage, Buff, Combat, Versatile
>
>Item Tags: Damage Buff Combat
>
>The Sunless Citadel, pg. 229
 
When imported into Foundry the resulting item was a potion:
![afbeelding](https://user-images.githubusercontent.com/5552116/204793775-c168dbb6-dccb-4963-a101-0c8656a81d6e.png)

It this by design? Or not yet implemented? Or am I doing something wrong here?

To make it easier to test I tried it also with a weapon from the SRT which is also imported as a potion: https://www.dndbeyond.com/magic-items/5407-ammunition-1

>Ammunition, +1
>Weapon (any ammunition), uncommon
>
>You have a +1 bonus to attack and damage rolls made with this piece of magic ammunition. Once it hits a target, the ammunition is no longer magical.
>
>Applicable Ammunition:
>
>[Arrows](https://www.dndbeyond.com/magic-items/4839-arrows-1), [Blowgun Needles](https://www.dndbeyond.com/magic-items/1730854-blowgun-needles-1), [Crossbow Bolts](https://www.dndbeyond.com/magic-items/4567-crossbow-bolts-1) and [Sling Bullets](https://www.dndbeyond.com/magic-items/4846-sling-bullets-1).
>
> 
>
>Notes: Bonus: Magic, Damage
>
>Item Tags: Damage
>
>Basic Rules, pg. 150

**Comment by jbhaywood** [comment]
The module is meant to import creature stat blocks only, monsters and NPCs. I’m surprised it worked at all for a single item. The idea of making an importer for items is kind of interesting, but I don’t have any time to work on that right now.
