### ISSUE TITLE
Feature Request: Specify a folder to import to

### ISSUE THREAD

**Issue by mowngle** [jbhaywood/5e-statblock-importer#39]
Hey, I love your tool.  I'd like to make a suggestion, if I had the option of selecting which folder or subfolder to import my actor to, that would greatly simplify my life.  I've got a billion subfolders, and clicking and dragging each actor can be tedious.  (Not as tedious as creating a new stat block from scratch, mind you).  

Thanks for doing what you do!

**Comment by jbhaywood** [comment]
Ask and you shall receive. Update to version 1.6 and you'll see the new option.
