### ISSUE TITLE
Armor class, Legendary Resistance and Lair Actions

### ISSUE THREAD

**Issue by MSAbaddon** [jbhaywood/5e-statblock-importer#4]
Hi there,
with the current DnD5E release armor class was changed to being calculated. I think you need to change your module slightliy to get the correct AC imported.

In addition to that - while the Legendary Resistance reaction is imported corectly, it would be great if this would also update the Legendary Resistance counter within the NPC sheet.

Last question: Does your module also import Lair Actions (e.g. Lich)?

**Comment by jbhaywood** [comment]
Can you post an example of the new armor class format?

I can get that added. Shouldn't be a problem.

It will import Lair Actions and Regional Effects right now. Let me know if you have any issues with it.

**Comment by MSAbaddon** [comment]
Well, I can try.

Actually there might be two versions of AC calculation: Natural Armor and Worn Armor.

**Worn Armor (e.g. Goblin)**

Goblin
Small humanoid (goblinoid) , neutral evil
Armor Class 15 (Leather Armor, Shield)
Hit Points 7 (2d6)
Speed 30 ft.
STR
8 (-1)
DEX
14 (+2)
CON
10 (+0)
INT
10 (+0)
WIS
8 (-1)
CHA
8 (-1)
Skills Stealth +6
Senses Darkvision 60 ft., Passive Perception 9
Languages Common, Goblin
Challenge 1/4 (50 XP)
Nimble Escape. The goblin can take the Disengage or Hide action as a bonus action on each of its turns.
Actions
Scimitar. Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) slashing damage.
Shortbow. Ranged Weapon Attack: +4 to hit, range 80/320 ft., one target. Hit: 5 (1d6 + 2) piercing damage.

He gets his AC due to having a Leather Armor and a Shield equipped. Correct way to get this done would be to add both items to his inventory, set them to equipped and set the AC calculation method to Equipped Armor. Equipped Armor actualls is the default calculation method, so adding the items should be enough to get the correct AC.

![image](https://user-images.githubusercontent.com/66370966/129418126-5d3a4207-55cb-48ec-a9f6-d9be1472a3d5.png)

**Natural Armor (e.g. Black Bear)**

Black Bear
Medium beast , unaligned
Armor Class 11 (Natural Armor)
Hit Points 19 (3d8 + 6)
Speed 40 ft., climb 30 ft.
STR
15 (+2)
DEX
10 (+0)
CON
14 (+2)
INT
2 (-4)
WIS
12 (+1)
CHA
7 (-2)
Skills Perception +3
Senses Passive Perception 13
Languages --
Challenge 1/2 (100 XP)
Keen Smell. The bear has advantage on Wisdom (Perception) checks that rely on smell.
Actions
Multiattack. The bear makes two attacks: one with its bite and one with its claws.
Bite. Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.
Claws. Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4 + 2) slashing damage.

For a creature using Natural Armor you need to set the calculation method to "natural" and insert the actual value as a flat value I think.

![image](https://user-images.githubusercontent.com/66370966/129418605-8252be3c-f1c4-433e-9af6-cbb47a5cf3a4.png)

**Comment by jbhaywood** [comment]
All of the requests have been added in v1.1.0.

**Comment by MSAbaddon** [comment]
Great work, thanks :-)
One more thing though - I just saw that there also exists a calculation method "natural". That would be more apppropriate for the NPCs that have natural armor. Benefit of this calculation type: If you add e.g. a shield after the import, the bonus ac from the item is added to the AC. If it is set to flat, the bonus AC is ignored.

**Comment by MSAbaddon** [comment]
Ok, just tried to import a Lich including Lair Actions. Most of the import looks great, however there are a few things that could be improved :-)
- Currently, one Feature "Legendary Actions" is created with the general text and the different abilities. Would be great if this feature only contains the general text and if the different abilities get separate ability entries with the correct number of legendary actions used (the screenshot below is taken from the lich in the srd compendium)
![image](https://user-images.githubusercontent.com/66370966/129854846-40788d94-47a8-4e75-8fdd-fb57c4b68a28.png)
- Same goes with the lair actions, currently they are all within one feature, the DnD5 system however has explicit "Lair Action" action costs, so again, the general text can remain, the different abilities could be separated in different Lair Action abilities.
- Currently the different features a creature has are displayed in the "Actions" section, because their action cost is set to "none". You instead could simply leave the field blank, that would transfer the features to the feature section. Exeption here is the Legendary Resistance, this can remain at "None" or - even better - at "Special"
![image](https://user-images.githubusercontent.com/66370966/129855473-f6d24a06-2b6e-44df-93c5-b1f973da74ed.png)



This is the stat block I used (taken from DnD Beyond)
Lich
Medium undead , any evil alignment
Armor Class 17 (Natural Armor)
Hit Points 135 (18d8 + 54)
Speed 30 ft.
STR
11 (+0)
DEX
16 (+3)
CON
16 (+3)
INT
20 (+5)
WIS
14 (+2)
CHA
16 (+3)
Saving Throws CON +10, INT +12, WIS +9
Skills Arcana +19, History +12, Insight +9, Perception +9
Damage Resistances Cold, Lightning, Necrotic
Damage Immunities Poison; Bludgeoning, Piercing, and Slashing from Nonmagical Attacks
Condition Immunities Charmed, Exhaustion, Frightened, Paralyzed, Poisoned
Senses Truesight 120 ft., Passive Perception 19
Languages Common plus up to five other languages
Challenge 21 (33,000 XP)
Legendary Resistance (3/Day). If the lich fails a saving throw, it can choose to succeed instead.
Rejuvenation. If it has a phylactery, a destroyed lich gains a new body in 1d10 days, regaining all its hit points and becoming active again. The new body appears within 5 feet of the phylactery.
Spellcasting. The lich is an 18th-level spellcaster. Its spellcasting ability is Intelligence (spell save DC 20, +12 to hit with spell attacks). The lich has the following wizard spells prepared:
Cantrips (at will): mage hand, prestidigitation, ray of frost
1st level (4 slots): detect magic, magic missile, shield, thunderwave
2nd level (3 slots): acid arrow, detect thoughts, invisibility, mirror image
3rd level (3 slots): animate dead, counterspell, dispel magic, fireball
4th level (3 slots): blight, dimension door
5th level (3 slots): cloudkill, scrying
6th level (1 slot): disintegrate, globe of invulnerability
7th level (1 slot): finger of death, plane shift
8th level (1 slot): dominate monster, power word stun
9th level (1 slot): power word kill
Turn Resistance. The lich has advantage on saving throws against any effect that turns undead.
Actions
Paralyzing Touch. Melee Spell Attack: +12 to hit, reach 5 ft., one creature. Hit: 10 (3d6) cold damage. The target must succeed on a DC 18 Constitution saving throw or be paralyzed for 1 minute. The target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.
Legendary Actions
The lich can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The lich regains spent legendary actions at the start of its turn.
Cantrip. The lich casts a cantrip.
Paralyzing Touch (Costs 2 Actions). The lich uses its Paralyzing Touch.
Frightening Gaze (Costs 2 Actions). The lich fixes its gaze on one creature it can see within 10 feet of it. The target must succeed on a DC 18 Wisdom saving throw against this magic or become frightened for 1 minute. The frightened target can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success. If a target's saving throw is successful or the effect ends for it, the target is immune to the lich's gaze for the next 24 hours.
Disrupt Life (Costs 3 Actions). Each non-undead creature within 20 feet of the lich must make a DC 18 Constitution saving throw against this magic, taking 21 (6d6) necrotic damage on a failed save, or half as much damage on a successful one.
Lair Actions
On initiative count 20 (losing initiative ties), the lich can take a lair action to cause one of the following magical effects; the lich can’t use the same effect two rounds in a row:
The lich rolls a d8 and regains a spell slot of that level or lower. If it has no spent spell slots of that level or lower, nothing happens.
The lich targets one creature it can see within 30 feet of it. A crackling cord of negative energy tethers the lich to the target. Whenever the lich takes damage, the target must make a DC 18 Constitution saving throw. On a failed save, the lich takes half the damage (rounded down), and the target takes the remaining damage. This tether lasts until initiative count 20 on the next round or until the lich or the target is no longer in the lich’s lair.
The lich calls forth the spirits of creatures that died in its lair. These apparitions materialize and attack one creature that the lich can see within 60 feet of it. The target must succeed on a DC 18 Constitution saving throw, taking 52 (15d6) necrotic damage on a failed save, or half as much damage on a success. The apparitions then disappear.

**Comment by jbhaywood** [comment]
> One more thing though - I just saw that there also exists a calculation method "natural". That would be more apppropriate for the NPCs that have natural armor. Benefit of this calculation type: If you add e.g. a shield after the import, the bonus ac from the item is added to the AC. If it is set to flat, the bonus AC is ignored.

If the statblock says "(natural armor" next to the armor class, it will be set as "natural" in Foundry. But if there's no identifier at all, for example something like "Armor Class 12", it's set as "flat". You could argue that no identifier should be set as "natural" too so that it calculates custom added armor correctly. I see a lot of cases where sometimes an animal with have "(natural armor)" in the armor class and sometimes nothing. It's pretty inconsistent. 

What do you think?

**Comment by jbhaywood** [comment]
Can you move the comment about the Lich to a new issue so I can track it and comment on it? Thanks.

**Comment by MSAbaddon** [comment]
Setting armor calc to natural when it it's indicated in the stat block as well as setting it to flat when there is no indicator is fine :-)

I'll open a new issue with the lich stat block.
