### ISSUE TITLE
Missing Creature Type

### ISSUE THREAD

**Issue by IronWarjack** [jbhaywood/5e-statblock-importer#41]
So far everything looks great but Creature Type is not importing.

Including screen shot of the stat block and the results: https://i.imgur.com/7Mmm0yf.png

Here is book entry: https://i.imgur.com/MaFvqtP.png

**Comment by jbhaywood** [comment]
Can you post the text that you used? That would make it easier for me to test with it and see what's going on.

**Comment by IronWarjack** [comment]
Happy to:

Wrecker
Medium humanoid, any alignment
Armor Class 11 (leather armor)
Hit Points 32 (5d8 + 10)
Speed 30 ft.
STR DEX CON INT WIS CHA
15 (+2) 12 (+1) 15 (+2) 10 (+0) 10 (+0) 10 (+0)
Senses passive Perception 11
Languages any one language
Challenge 1/2 (100 XP)
Hold Breath. The wrecker can hold its breath for 5 minutes.
Knockout Strike (Recharge 5–6). When the wrecker hits a
target with a melee weapon attack, the target must succeed on
a DC 12 Constitution saving throw or be stunned until the end
of the creature’s next turn. If the target is already stunned, it is
knocked unconscious instead.
Actions
Multiattack. The wrecker makes two melee attacks.
Belaying Pin. Melee Weapon Attack: +4 to hit, reach 5 ft., one
target. Hit: 5 (1d6 + 2) bludgeoning damage.
Pistol. Ranged Weapon Attack: +3 to hit, range 30/90 ft., one
target. Hit: 5 (1d8 + 1) piercing damage.

**Comment by FrankIsAtank** [comment]
I have the same issue. I tested it with the standard zombie stat block from the basic rules, and it fails to register as undead.

Foundry 10 build 291
Dnd5e 2.1.2
Statblock Importer 1.5.8

**Comment by JPMeehan** [comment]
I can even replicate with the sample Glabrezu stat block.
Foundry 10 build 291
System 2.1.2
Module 1.6

**Comment by jbhaywood** [comment]
Fixed in version 1.61.
