### ISSUE TITLE
Compatible with another language?

### ISSUE THREAD

**Issue by Padhiver** [jbhaywood/5e-statblock-importer#42]
Hello !
I was wondering if making your module compatible with French statblocks would be something possible?
I tested a little bit, and unfortunately for the moment it works only partially, as soon as the module meets a French term, the import goes wrong. :P
Thank you !

**Comment by jbhaywood** [comment]
I'd love to make this work with other languages, but it would be a large effort. I'm going to have to close this since I just don't have the time to put into it.
