### ISSUE TITLE
Few Errors on one monster

### ISSUE THREAD

**Issue by CampbellSoupDC** [jbhaywood/5e-statblock-importer#43]
- I took its stats from different sources and each time got errors. I think its something to do with its Stat numbers. in both of them, they are not correct but both are the same not correct.
- Sourcebook (thought bad formatting from copy. even tried editing and cleaning up.)
- https://dr-eigenvalue.github.io/bestiary/ (things misspaced but fixable with periods but still errors and stat blocks are wonky.)
- it seems on this one it doesn't read Keen Senses as a feature. it has 9 (0) 11 (0) its numbers for int and wis before reading keen senses.
- exact error code and what was pasted below with screenshots.
- let me know if I didn't put everything you need or anything I can try to do. 

© Model Validation Errors [Actor5e.system]: Model Validation Errors [NPCData.abilities]: Model Validation Errors [wis]: Model Validation Errors [value]: must be an integer [cha]: Model Validation Errors (value]: must be an integer

### 1. Sourcebook 

DIRE TROLL
......
•' .
Huge giant, chaotic evil ,
Armor Class 15 (natural armor)
Hit Points 172 (15dl 2 + 75) •
Speed 40 ft.
..
STR DEX CON INT WIS CHA
22 (+6) 15 (+2) 21 (+5)
Saving Throws Wis +5, Cha +2
Skills Perception +5
9 (-1) 11 (+O) 5 (-3)
....
Damage Resistances bludgeoning, piercing, and slashing from
nonmagical attacks
Condition Immunities frightened, poisoned
Senses darkvision 60 ft., passive Perception 15
Languages Giant ...,_
Challenge 13 (10,000 XP) ,. •
Keen Senses. The troll has advantage on Wisdom (Perception)
checks that rely on smell or sight.
Regeneration. The troll regains 10 hit points at the start of its
turn. If the troll takes acid or fi re damage, it regains only 5 hit
points at the start of its next turn. The troll dies only if it is hit
by an attack that deals 10 or more acid or fire damage while the
troll has 0 hit points.
ACTIONS
Multiattack. The troll makes five attacks: one with its bite and
four with its claws.
Bite. Melee Weapon Attack: +11 to hit, reach 10 ft., one
target. Hit: 10 (ld8 + 6) piercing damage plus 5 (ldlO) poison
damage.
Claws. Melee Weapon Attack: +11 to hit, reach 10 ft. , one target.
Hit: 16 (3d6 + 6) slashing damage.
Whirlwind of Claws (Recharge 5-6). Each creature within 10
feet of the troll must make a DC 19 Dexterity saving throw, taking
44 (8dl0) slashing damage on a fai led save, or half as much
damage on a successful one.

### 2. Website

Dire Troll
Huge giant, chaotic evil
Armor Class 15 (natural armor)
Hit Points 172 (15d12 + 75)
Speed 40 ft.
STR
22 (+6)

 
DEX
15 (+2)

 
CON
21 (+5)

 
INT
9 (0)

 
WIS
11 (0)

 
CHA
5 (-2)

Damage Resistances bludgeoning, piercing, and slashing from nonmagical attacks
Condition Immunities frightened, poisoned
Senses darkvision 60 ft., passive Perception 15
Saving Throws Wis +5, Cha +2
Skills Perception +5
Languages Giant
Challenge 13 (10,000 XP)
Keen Senses. The troll has advantage on Wisdom (Perception) checks that rely on smell or sight.

Regeneration. The troll regains 10 hit points at the start of its turn. If the troll takes acid or fire damage, it regains only 5 hit points at the start of its next turn. The troll dies only if it is hit by an attack that deals 10 or more acid or fire damage while the troll has 0 hit points.

Actions
Multiattack The troll makes five attacks: one with its bite and four with its claws.

Bite Melee Weapon Attack: +11 to hit, reach 10 ft., one target. Hit: 10 (1d8 + 6) piercing damage plus 5 (1d10) poison damage.

Claws Melee Weapon Attack: +11 to hit, reach 10 ft., one target. Hit: 16 (3d6 + 6) slashing damage.

Whirlwind of Claws (Recharge 5-6) Each creature within 10 feet of the troll must make a DC 19 Dexterity saving throw, taking 44 (8d10) slashing damage on a failed save, or half as much damage on a successful one.

![Screen Shot 2023-01-17 at 1 55 21 AM](https://user-images.githubusercontent.com/122861067/212836877-21f57ba5-029e-407f-9f35-49ca847d667a.png)

![Screen Shot 2023-01-17 at 2 25 59 AM](https://user-images.githubusercontent.com/122861067/212836477-50d3ece9-7971-4a17-a2ea-8c21e60d3a39.png)
![Screen Shot 2023-01-17 at 2 26 09 AM](https://user-images.githubusercontent.com/122861067/212836505-bf3d1731-b38d-4f18-a4cc-70893f3984d6.png)

**Comment by jbhaywood** [comment]
Thanks for all the information. It should be fixed in version 1.62. The problem was with the ability scores that had "(0)" next to the number. Usually it's written as "(+0)". But I updated the parser to handle the missing plus sign.
