### ISSUE TITLE
Import vehicles

### ISSUE THREAD

**Issue by bodgingbrom** [jbhaywood/5e-statblock-importer#44]
Not technically an issue, but vehicle imports are not currently possible. Is there work being done to add that option?

Appreciate your work on this, you saved me 30+ hours of work already.

**Comment by jbhaywood** [comment]
I don't have any plans to support vehicles right now. I'll leave this open in case I get some time in the future or someone else wants to take it on.

**Comment by jbhaywood** [comment]
Closing because no one has picked it up.
