### ISSUE TITLE
Lair Actions

### ISSUE THREAD

**Issue by LadyLuxon** [jbhaywood/5e-statblock-importer#45]
Hi, 

Thanks for this module, it saves so much time! 

That said, there seems to have a small issue with Lair actions at the moment: they set themselves as Features instead of Lair actions in the stat block. From looking at the code, I believe it is due to the activation type not being given for lair actions the same way it is for legendary! 

![image](https://user-images.githubusercontent.com/110874303/221371365-37ba586c-003d-4230-9449-91b441722108.png)

In the meantime, it is very little effort to change the activation type manually, what with everything else being done automatically, but I wanted to rise it with you nonetheless! 

Again, thanks for this!

**Comment by jbhaywood** [comment]
Thanks for pointing this out. It should be fixed in v1.63.
