### ISSUE TITLE
Feature Request: Option to add compendium prioritization when importing?

### ISSUE THREAD

**Issue by nyxalteria** [jbhaywood/5e-statblock-importer#47]
Is it possible to add a setting to choose which compendiums are prioritized when it selects spells / features for importing? E.G I have several compendiums with automation set up for spells and features but its prioritizing SRD 5.1.

**Comment by jbhaywood** [comment]
With version 1.65 it now looks through the SRD compendium packs last, so it should find your custom spells first and use them instead of the standard ones.
