### ISSUE TITLE
Failed Import

### ISSUE THREAD

**Issue by nyxalteria** [jbhaywood/5e-statblock-importer#48]
Aarakocra Talon of Syranita
Medium Humanoid (Aarakocra), Typically Neutral Good
Armor Class 13
Hit Points 84 (13d8 + 26)
Speed 20 ft., fly 50 ft.
STR DEX CON INT WIS CHA
10 (+0) 16 (+3) 14 (+2) 11 (+0) 17 (+3) 11 (+0)
Skills Nature +6, Perception +9, Stealth +9, Survival +9
Senses passive Perception 19
Languages Aarakocra, Auran
Challenge 5 (1,800 XP) Proficiency Bonus +3
Dive Attack. If the aarakocra is flying and dives at least 30 feet
straight toward a target and then hits it with a melee weapon attack,
the attack deals an extra 7 (2d6) damage to the target.
Actions
Multiattack. The aarakocra makes two Talon attacks or uses Lancing
Wind twice.
Talon. Melee Weapon Attack: +6 to hit, reach 5 ft., one target.
Hit: 5 (1d4 + 3) slashing damage plus 4 (1d8) lightning damage.
Lancing Wind. Ranged Spell Attack: +6 to hit, range 120 ft., one
target. Hit: 12 (2d8 + 3) force damage. If the target is a Large or
smaller creature, it must succeed on a DC 14 Strength saving throw
or be knocked prone.
Spellcasting. The aarakocra casts one of the following spells using
Wisdom as the spellcasting ability (spell save DC 14, +6 to hit with
spell attacks):
At will: light, guidance, thaumaturgy, word of radiance
2/day each: cure wounds, call lightning
1/day each: beacon of hope, conjure elemental (air), freedom of
movement, ice storm
Bonus Actions
Fury of Syranita (3/Day). The aarakocra causes its melee or ranged
weapon attacks to magically deal an extra 7 (2d6) lightning or
thunder damage to a target on a hit. This benefit lasts until the end of
the turn.
Legendary Actions
The aarakocra can take 3 legendary actions, choosing from the
options below. Only one legendary action option can be used at a time
and only at the end of another creature's turn. The aarakocra regains
spent legendary actions at the start of its turn.
Attack. The aarakocra makes a Talon attack or uses Lancing Wind.
Cast a Spell (Costs 2 Actions). The aarakocra uses Spellcasting.
Wings of Syranita (Costs 2 Actions). The aarakocra beats its wings
and summons friendly winds from Syranita. Each enemy creature
within 20 feet of the aarakocra must succeed on a DC 14 Dexterity
saving throw or take 13 (3d8) bludgeoning damage, pushed up
to 10 feet away from the aarakocra, and be knocked prone. On a
successful save, a creature takes half as much damage and isn't
pushed or knocked prone.

Spells fail to import correctly, it just gives normal spell slots and doesn't input the daily usages. I've tried various formatting fixes with no luck. This has happened for several statblocks from several different books from different publishers. (Kobold Press etc, this one being from Monster Manual Expanded I by Dragonix on DMs Guild)

**Comment by jbhaywood** [comment]
What do you mean by "just gives normal spell slots"? What are you expecting exactly?

**Comment by nyxalteria** [comment]
So this is what I was expecting, for some statblocks it does this and others it doesn't.
![image](https://user-images.githubusercontent.com/92659516/231891871-0b1e3ac3-3e01-410c-b65f-b898fb2ed1d2.png)
If you take a look at the monster stat block above it shows limited daily usages.
But using the statblock above this is what I get:
![image](https://user-images.githubusercontent.com/92659516/231892138-a01357a2-28ed-4ea5-8cf3-b1439cf99f8d.png)
It's showing normal spell slots like it would possibly be a class or something. And not accounting for the limited usages listed.

**Comment by nyxalteria** [comment]
here's an example of where it imports correctly including the statblock
![image](https://user-images.githubusercontent.com/92659516/231894587-bc22321b-ec93-406c-b344-4ec35164c258.png)
POENA, DUKE OF RETRIBUTION
Large fiend (devil), lawful evil
Armor Class 18 (plate)
Hit Points 231 (22d10 + 110)
Speed 30 ft., fly 60 ft.
STR DEX CON INT WIS CHA
24 (+7) 18 (+4) 20 (+5) 21 (+5) 20 (+5) 24 (+7)
Saving Throws Dex +11, Con +12, Wis +12, Cha +13
Damage Resistances cold; bludgeoning, piercing, and slashing from
nonmagical attacks not made with silvered weapons
Damage Immunities fire, poison
Condition Immunities poisoned
Senses truesight 120 ft., passive Perception 15
Languages Infernal, telepathy 120 ft.
Challenge 19 (22,000 XP)
Face of the Fallen. As a bonus action, Poena transforms her face
into victims her attackers recognize. Each creature within 30 feet
of her that can see her sees the face of a person it has wronged
and must succeed on a DC 19 Wisdom saving throw or have
disadvantage on attack rolls against Poena until the end of its
next turn.
Legendary Resistance (3/Day). If Poena fails a saving throw, she can
choose to succeed instead.
Magic Resistance. Poena has advantage on saving throws against
spells and other magical effects.
Magic Weapons. Poena’s weapon attacks are magical.
Innate Spellcasting. Poena’s innate spellcasting ability is Charisma
(spell save DC 21). She can innately cast the following spells,
requiring no material components:
At will: alter self (can become Medium when changing her
appearance), bane, hold person, locate creature
3/day each: flame strike, phantasmal killer
1/day each: finger of death
ACTIONS
Multiattack. Poena makes three attacks: one with her bladed
whip and two with her longsword. Alternatively, she makes three
longbow attacks.
Bladed Whip. Melee Weapon Attack: +13 to hit, reach 15 ft., one
target. Hit: 16 (2d8 + 7) slashing damage. If the target is a creature
other than an undead or a construct, it must succeed on a DC 19
Constitution saving throw or lose 14 (4d6) hp at the start of each
of its turns as a blade of retributive energy lodges itself in the
wound. Any creature can take an action to remove the blade with a
successful DC 16 Wisdom (Medicine) check. The blade crumbles to
dust if the target receives magical healing.
Longsword. Melee Weapon Attack: +13 to hit, reach 5 ft., one target.
Hit: 16 (2d8 + 7) slashing damage, or 18 (2d10 + 7) slashing damage
if used with two hands.
Longbow. Ranged Weapon Attack: +10 to hit, range 150/600 ft., one
target. Hit: 13 (2d8 + 4) piercing damage.
LEGENDARY ACTIONS
Poena can take 3 legendary actions, choosing from the options
below. Only one legendary action can be used at a time and only at
the end of another creature’s turn. Poena regains spent legendary
actions at the start of her turn.
Mark for Death. Poena chooses a creature she can see and marks
it as her quarry. She deals an extra 2d6 damage to her target
whenever she hits it with a weapon attack, and she has advantage
on any Wisdom (Perception) or Wisdom (Survival) check she makes
to find it. The mark remains until Poena chooses a new target or
until her quarry dies.
Swift Wings. Poena flies up to half her flying speed.
Attack (Cost 2 Actions). Poena makes one longsword attack.

I am unsure of what the difference is between the two but several other statblocks like this from the same source (TOB2 kobold press) fail to import like the above, and just import like what was shown on your readme. The following being another example that fails to import correctly: 

MEAD ARCHON
Medium celestial, chaotic good
Armor Class 14 (leather armor)
Hit Points 82 (11d8 + 33)
Speed 30 ft., fly 60 ft.
STR DEX CON INT WIS CHA
20 (+5) 16 (+3) 17 (+3) 14 (+2) 18 (+4) 20 (+5)
Saving Throws Con +5, Wis +6, Cha +7
Skills Athletics +7
Damage Resistances poison, radiant; bludgeoning, piercing, and
slashing damage from nonmagical attacks
Condition Immunities charmed, exhaustion, frightened, poisoned
Senses darkvision 60 ft., passive Perception 14
Languages all, telepathy 60 ft.
Challenge 4 (1,100 XP)
Magic Resistance. The mead archon has advantage on saving
throws against spells and other magical effects.
Magic Weapons. The mead archon’s weapon attacks are magical.
Innate Spellcasting. The mead archon’s spellcasting ability is
Charisma (spell save DC 15). The archon can innately cast the
following spells, requiring only verbal components:
1/day each: aid, enhance ability, lesser restoration, protection from
poison, zone of truth
ACTIONS
Multiattack. The mead archon makes two melee attacks.
Alternatively, it can use its Radiant Bolt twice. It can use its Drunken
Touch in place of one melee attack.
Maul. Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 12
(2d6 + 5) bludgeoning damage.
Radiant Bolt. Ranged Spell Attack: +7 to hit, range 60 ft., one target.
Hit: 10 (3d6) radiant damage.
Drunken Touch. The mead archon touches a creature within 5 feet of
it. The creature must succeed on a DC 15 Constitution saving throw
or become poisoned for 1 hour. If a creature poisoned this way
takes damage, it can repeat the saving throw, ending the condition
on a success.
Create Potion of Healing (1/Day). The mead archon touches a
container containing 1 pint of alcohol and turns it into a potion of
healing. If the potion is not consumed within 24 hours, it reverts
back to its original form.
Divine Guzzle (Recharge 4–6). The mead archon drinks a pint of
alcohol and chooses one of the following effects:
• The archon belches fire in a 15-foot cone. Each creature in that
area must make a DC 15 Dexterity saving throw, taking 14 (4d6)
fire damage on a failed save, or half as much damage on a
successful one.
• The archon has advantage on attack rolls and saving throws until
the end of its next turn.
• The archon regains 10 hit points.

**Comment by nyxalteria** [comment]
Here's another example of a statblock that imports with the desired result, not sure if this will help but I thought i'd post it since there's been a mishmash of failed to import (a la first statblock provided) and correctly imports 

AUGUST ROOSTER
Medium monstrosity, neutral evil
Armor Class 14 (natural armor)
Hit Points 75 (10d8 + 30)
Speed 25 ft.
STR DEX CON INT WIS CHA
10 (+0) 17 (+3) 16 (+3) 8 (–1) 7 (–2) 18 (+4)
Damage Resistances psychic
Condition Immunities charmed
Senses passive Perception 8
Languages Common
Challenge 4 (1,100 XP)
Aura of Subservience. A beast or humanoid that ends its turn
within 30 feet of the august rooster and can see or hear it must
succeed on a DC 14 Wisdom saving throw or be charmed for 1 day.
A charmed creature that moves more than 100 feet away from the
august rooster ceases to be charmed. If the august rooster requests
that a charmed creature do more than tend to the creature’s own
needs, pay devotion to the august rooster, or bring the rooster food
and gifts, the charmed creature can make a new saving throw with
advantage. If a creature’s saving throw is successful or the effect
ends for it, the creature is immune to the august rooster’s Aura of
Subservience for 24 hours.
Dive Bomb. If the august rooster is flying and moves at least 20 feet
straight toward a target and then hits it with a talon attack on the
same turn, the target takes an extra 7 (2d6) slashing damage.
Jumper. The august rooster can fly up to 40 feet on its turn, but
it must start and end its movement on a solid surface such as a
roof or the ground. If it is flying at the end of its turn, it falls to the
ground and takes falling damage.
Innate Spellcasting. The august rooster’s innate spellcasting ability
is Charisma (spell save DC 14). The august rooster can innately cast
the following spells, requiring no material components.
At will: dancing lights, mage hand, message, vicious mockery
3/day each: bane, charm person, hideous laughter
1/day each: healing word, hold person
ACTIONS
Multiattack. The august rooster makes two talon attacks.
Talon. Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10
(2d6 + 3) slashing damage.

**Comment by nyxalteria** [comment]
I'm on foundry 10.291 if that helps, and the latest 5e system update / latest update of this module

**Comment by jbhaywood** [comment]
Thanks for all the info. These should be fixed in v1.66.
