### ISSUE TITLE
Failed import (creature type)

### ISSUE THREAD

**Issue by nyxalteria** [jbhaywood/5e-statblock-importer#49]
It doesn't import the creature type. here's the statblock. It does this for several of the statblocks from the same book, Monster manaul I expanded. (and the latter books in the series)

Aboleth Slime Lord
Large Aberration, Typically Lawful Evil
Armor Class 18 (natural armor)
Hit Points 195 (23d10 + 69)
Speed 10 ft., swim 40 ft.
STR DEX CON INT WIS CHA
22 (+6) 9 (-1) 16 (+3) 18 (+4) 16 (+3) 18 (+4)
Saving Throws Con +8, Int +9, Wis +8
Skills History +14, Perception +13
Damage Immunities acid
Senses darkvision 120 ft., passive Perception 23
Languages Deep Speech, telepathy 120 ft.
Challenge 14 (11,500 XP) Proficiency Bonus +5
Amphibious. The aboleth can breathe air and water.
Acidic Mucous Cloud. While underwater, the aboleth is surrounded
by transformative mucus. A creature that touches the aboleth or that
hits it with a melee attack while within 5 feet of it takes 7 (2d6) acid
damage and must succeed on a DC 16 Constitution saving throw.
On a failure, the creature is diseased for 1d4 hours. The diseased
creature can breathe only underwater.
Probing Telepathy. If a creature communicates telepathically with
the aboleth, the aboleth learns the creature's greatest desires if the
aboleth can see the creature.
Actions
Multiattack. The aboleth makes three Tentacle attacks. Alternatively,
it can use two Slime Orb attacks.
Slime Orb. Ranged Spell Attack: +11 to hit, range 120 ft., one target.
Hit: 14 (4d6) acid damage and the target must succeed on a DC 16
Strength saving throw or be restrained until the end of the aboleth's
next turn.
Tentacle. Melee Weapon Attack: +11 to hit, reach 10 ft., one target.
Hit: 13 (2d6 + 6) bludgeoning damage plus 10 (3d6) acid damage.
If the target is a creature, it must succeed on a DC 16 Constitution
saving throw or become diseased. The disease has no effect for 1
minute and can be removed by any magic that cures disease. After 1
minute, the diseased creature's skin becomes translucent and slimy,
the creature can't regain hit points unless it is underwater, and the
disease can be removed only by heal or another disease-curing spell
of 6th level or higher. When the creature is outside a body of water,
it takes 6 (1d12) acid damage every 10 minutes unless moisture is
applied to the skin before 10 minutes have passed.
Tail. Melee Weapon Attack: +11 to hit, reach 10 ft., one target.
Hit: 15 (3d6 + 5) bludgeoning damage plus 10 (3d6) acid damage.
Enslave (3/Day). The aboleth targets one creature it can see within
30 feet of it. The target must succeed on a DC 16 Wisdom saving
throw or be magically charmed by the aboleth until the aboleth dies
or until it is on a different plane of existence from the target. The
charmed target is under the aboleth's control and can't take reactions,
and the aboleth and the target can communicate telepathically with
each other over any distance.
Whenever the charmed target takes damage, the target can repeat
the saving throw. On a success, the effect ends. No more than once
every 24 hours, the target can also repeat the saving throw when it is
at least 1 mile away from the aboleth.
Legendary Actions
The aboleth can take 3 legendary actions, choosing from the options
below. Only one legendary action option can be used at a time and
only at the end of another creature's turn. The aboleth regains spent
legendary actions at the start of its turn.
Tail Swipe. The aboleth makes one Tail attack.
Psychic Drain (Costs 2 Actions). One creature charmed by the
aboleth takes 17 (5d6) psychic damage, and the aboleth regains hit
points equal to the damage the creature takes.
Slime Sphere (Costs 3 Actions). The aboleth conjures a ball of
acidic slime that explodes at a point it can see within 120 feet of
it. Each creature in a 20-foot-radius sphere centered on that point
must succeed on a DC 16 Strength saving throw. On a failed save, a
creature takes 14 (4d6) acid damage and is restrained until until it
escapes the slime. Any creature can use its action to make a DC 16
Strength check to free itself or another creature in the net, ending
the effect on a success. Dealing 10 fire damage to the slime (AC 12)
destroys the slime and frees the target. A restrained creature takes
10 (3d6) acid damage at the start of each of the Aboleth's turns. On
a successful save, a creature takes half as much damage and isn't
restrained.

**Comment by JPMeehan** [comment]
The issue here is that the type checking is case sensitive, and this past year WotC swapped from all lowercase to capitalizing the types.

**Comment by jbhaywood** [comment]
I'll look at this in a bit, but the parser doesn't check for letter case. It might be the "typically" throwing it off. It's possible that the Foundry 5e system doesn't support that as an identifier.

**Comment by jbhaywood** [comment]
Fixed in v1.67.
