### ISSUE TITLE
Import from DnD Beyond

### ISSUE THREAD

**Issue by MSAbaddon** [jbhaywood/5e-statblock-importer#5]
Hi there,
I have one more request.
Actually, your module not only works for the stat blocks from the srd document, but also for the DnD Beyond stat blocks, if you copy&paste them to your importer. A few manual adjustments need to be made though, and maybe you could implement them to your module.

That's how a stat block copied from DnD Beyond looks like:

>Black Bear
>Medium beast , unaligned
>
>Armor Class 11 (Natural Armor)
>Hit Points 19 (3d8 + 6)
>Speed 40 ft., climb 30 ft.
>
>STR
>15 (+2)
>DEX
>10 (+0)
>CON
>14 (+2)
>INT
>2 (-4)
>WIS
>12 (+1)
>CHA
>7 (-2)
>
>Skills Perception +3
>Senses Passive Perception 13
>Languages --
>Challenge 1/2 (100 XP)
>Proficiency Bonus +2
>
>Keen Smell. The bear has advantage on Wisdom (Perception) checks that rely on smell.
>
>Actions
>Multiattack. The bear makes two attacks: one with its bite and one with its claws.
>
>Bite. Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage.
>
>Claws. Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4 + 2) slashing damage.

Manual adjustments that currently need to be made:
- Delete the line with the Proficiency bonus
- Delete the blank lines

**Comment by jbhaywood** [comment]
Fixed with v1.1.1.
