### ISSUE TITLE
Failed to import statblock  

### ISSUE THREAD

**Issue by tmama1** [jbhaywood/5e-statblock-importer#50]
Wish I could provide further information but I copied a stat block from a PDF and plugged it in, only to be constantly met with an error and told to report it. The Console does not elaborate or tell me what I should mention in my report.

The Error read: **5E STATBLOCK IMPORTER: An error has occurred. Please report it using the module link so it can get fixed.**

The stat block itself is very generic also so I do not know what the issue was. It does seem to be creating an Actor using the details but only the first page of the character sheet so to speak (everything up to Challenge Rating)

I'll include the Statblock below but I do not know what further information I can provide.

<details><summary>Statblock</summary>
<p>
Sangzor (Druid)
Medium humanoid (human), neutral
Armor Class 16 (hide armor, shield)
Hit Points 132 (24d8 + 24)
Speed 30 ft.
STR DEX CON INT WIS CHA
10 (+0) 14 (+2) 12 (+1) 12 (+1) 20 (+5) 11 (+0)
Saving Throws Int +5, Wis +9
Skills Medicine +9, Nature, +5, Perception +9
Senses passive Perception 19
Languages understands Common, Druidic, and Draconic but
cannot speak
Challenge 12 (8,400 XP)
Spellcasting. Sangzor is an 18th-level spellcaster. His spellcasting
ability is Wisdom (spell save DC 17, +9 to hit with spell attacks).
He has the following druid spells prepared:
Cantrips (at will): primal savagery, mold earth, shape water,
thunderclap
1st level (4 slots): absorb elements, ice knife, snare
2nd level (3 slots): beast sense
3rd, 4th, 5th level (3 slots each): —
6th, 7th, 8th, 9th level (1 slot each): —
Mutilation. Sangzor's tongue has been cut out and he cannot
cast any spells with a verbal component.
Actions
Scimitar. Melee Weapon Attack: +6 to hit, reach 5 ft., one target.
Hit: 5 (1d6 + 2) slashing damage.
Goat Shape (2/Day). As a bonus action, Sangzor magically
polymorphs into monstrous goat, and can remain in this form for
up to 9 hours. He can choose whether its equipment falls to the
ground, melds with its new form, or is worn by the new form. He
reverts to his true form if he is knocked unconscious or dies, or if
his goat form falls to 0 hit points. Sangzor can revert to his true
form using a bonus action.
While in a goat form, Sangzor retains his game statistics, but
his AC, movement modes, Strength, Dexterity, and Constitution
are replaced by those of the goat form, and he gains any special
senses, proficiencies, traits, actions, and reactions (except class
features, legendary actions, and lair actions) that the goat form
has but that his true form lacks. He can cast spells with somatic
components in goat form.
The new form’s attacks count as magical for the purpose of
overcoming resistances and immunity to nonmagical attacks.
</p>
</details>

**Comment by jbhaywood** [comment]
The first thing I noticed by looking at this is that there are no line breaks. It’s just one big wall of text. You’ll need to manually add in returns so that the parser can understand it better.

**Comment by tmama1** [comment]
When pasted into the importer there are line breaks. When I pasted into
into the textbox there were line breaks. I'm unsure why it's returned with
none once posted.

I'll retry regardless in case it's user error, but I'm confident it's not.
If it were, how would it manage to read any of it but only import the
beginning?

Kindest Regards,

T.G.Mamalis

**Comment by jbhaywood** [comment]
In order to see what the problem is I need to reproduce it on my end, so I need to be able paste in exactly what you're pasting in. Maybe try not using the expander thing that hides the text in the comment here? Or use the Add Code option to paste here so that it doesn't try to format it.

**Comment by tmama1** [comment]
I apologize for my tardiness, I honestly should have reached out a lot
earlier.

To show you what text I am trying to import, I tried to find a different
stat block to recreate the issue. Once again only the first page of the
stat block copied over. That stat block, as copied from the pdf, is as
follows:

Gore Elemental
Large elemental, chaotic evil
Armor Class 16 (natural armor)
Hit Points 110 (13d10 + 39)
Speed 30 ft., climb 30 ft.
STR DEX CON INT WIS CHA
19 (+4) 13 (+1) 16 (+3) 3 (-4) 12 (+1) 7 (-2)
Damage Immunities poison
Damage Resistances bludgeoning, piercing, and
slashing damage from nonmagical weapons
Damage Vulnerabilities psychic
Condition Immunities exhaustion, grappled, paralyzed,
petrified, poisoned, prone, restrained, unconscious
Senses blindsight 60 ft. passive Perception 11
Languages Infernal
Challenge 6 (2300 XP) Proficiency Bonus +3
Actions
Gruesome Deluge. Melee Weapon Attack: +7 to hit, reach
10 ft., up to four targets. Hit: 8 (1d8 + 4) bludgeoning
damage plus 4 (1d8) necrotic damage. Each target of
Medium size or smaller must succeed on a DC 15 Strength
saving throw or be grappled (escape DC 15).
Grisly Mire. Each creature grappled by the gore elemental
must make a DC 15 Strength saving throw. On a failure,
a target takes 15 (2d10+4) slashing damage plus 5 (2d4)
necrotic damage and is knocked prone. Until it escapes
from the gore elemental’s grapple, the target is blinded,
restrained, and unable to breathe. If the saving throw is
successful, the target is pushed to an adjacent space.
Reactions
Swelling Crimson (1/Day). If the gore elemental reduces
a living creature to 0 hit points, its size increases to Huge.
The elemental gains advantage on all Strength and Constitution
saving throws, the gruesome deluge attack can
now grapple Large creatures, and the grisly mire attack
now deals 10 (4d4 + 4) slashing damage plus 7 (2d6) necrotic
damage on a failed saving throw. This condition lasts until
the gore elemental is reduced to less than 55 hit points.

Kind Regards,

T.G.Mamalis

**Comment by jbhaywood** [comment]
Sorry for the delay, but it looks like it imports ok. I've made some other changes since you first posted this, so maybe a fix for one of the other issues fixed this one too. Can you try it again with the latest version of the module?

**Comment by tmama1** [comment]
Thanks for the response James. The update did something as there is no
longer any error generated. Unfortunately, there is still nothing beyond
the first page, even when I try to remove the column format.
So i am unsure where the error is coming from

Kind Regards,

T.G.Mamalis

**Comment by jbhaywood** [comment]
This is what I'm seeing...

ATTRIBUTES
![image](https://user-images.githubusercontent.com/5131886/236742533-7eae6bf5-a496-41ce-a2b5-50977fe0fceb.png)

FEATURES
![image](https://user-images.githubusercontent.com/5131886/236742625-a04f87ce-5ae5-4e3b-9948-da07803d8532.png)

Do you see anything showing up in the Features tab? There's nothing beyond that because it doesn't have any spell or anything else.

**Comment by tmama1** [comment]
Afraid I don't even see the second screen, mine is completely empty

Kindest Regards,

T.G.Mamalis

**Comment by jbhaywood** [comment]
That's very odd. Maybe there's another module interfering with it? Have you tried using the [Find the Culprit](https://foundryvtt.com/packages/find-the-culprit/) module to check?

**Comment by tmama1** [comment]
That may be the answer, I will report back once I know where the conflict
was arising from.

Kind Regards,

T.G.Mamalis

**Comment by tmama1** [comment]
For context, I am running a published adventure. There was certain content
that was removed over time. In an attempt to recollect that content, the
adventure was redownloaded from Roll20 once more, but installed as a
Module. This seemed to be the culprit not allowing me to use your module
properly.

I would say this is now solved.

Kind Regards,

T.G.Mamalis
