### ISSUE TITLE
Importing Inventory Items/Loot?

### ISSUE THREAD

**Issue by zoonza** [jbhaywood/5e-statblock-importer#52]
I love the module and I've been trying to find a way to import items for an NPCs inventory but haven't had any success yet. Below is a list of items I'm trying to add to the stat block, as well as the formatting:

```
Inventory Items

Daggers - Boots carries several finely crafted daggers concealed within his clothing. These versatile weapons serve as both tools for his illicit activities and deadly implements in combat.
Studded Leather Armor - Boots wears light studded leather armor, providing him with moderate protection without impeding his agility.
Thieves' Tools - Boots possesses a set of specialized tools used for picking locks, disabling traps, and other acts of subterfuge. These tools enable him to carry out intricate heists and break-ins.
Potion of Invisibility - Boots keeps a single potion of invisibility, a valuable asset for his stealthy operations and escaping sticky situations.
Coin Pouch (2,000 gold) - Boots carries a small pouch containing 2,000 gold coins, representing his ill-gotten gains and his financial influence within the criminal underworld.
```

I've also tried `Inventory Items. Daggers -- Boots...` and listing it out in a paragraph format, as well as adding a "-" to each line item.

So far the inventory list that I've been trying to add has been added to the last Feature on the NPC stat block.

Did you intend for inventory items to be able to be added? Or is this something that's not currently supported?

Thank you!

**Comment by jbhaywood** [comment]
Hm, I've never seen inventory items in a statblock before so I haven't added support for it. Is this from a Wizards of the Coast source book?

**Comment by zoonza** [comment]
This isn't from a WotC sourcebook rather something that I was hoping to see using this module (and some others that connect well to it) in Foundry. This comes out of popular monster loot tables (for example: https://www.dmsguild.com/product/275550/Monster-Loot-Vol-1--Monster-Manual ) used for 5e, which I usually just end up adding items to enemy actors so that, when players defeat the enemy--or pickpocket an npc--they can grab items/coin.

**Comment by jbhaywood** [comment]
Oh I see. Yeah, that would be a different module. I want to keep this one focused only on reading statblocks. I've seen modules that keep adding new features and they end up being hard to maintain, hard to use, and more likely to conflict with other modules. It's just not worth it IMO.
