### ISSUE TITLE
Failed to import

### ISSUE THREAD

**Issue by baardaad** [jbhaywood/5e-statblock-importer#54]
### Versions
Foundry version:  **v11.302**
Dnd 5e: **2.2.1.** 

### Error messages
**First error message:** 
5E STATBLOCK IMPORTER: An error has occured. Please report it using the module link so it can get fixed.
**Second error message:** 
Cannot read properties of undefined (reading 'cha')
[Detected 2 packages: system:dnd5e, 5e-statblock-importer]

### Statblock 

**Crowned Monstrosity**
*Huge monstrosity (shapechanger), chaotic evil*

**Armor Class:** 18 (natural armor)
**Hit Points:** 400 (32d12 + 208)
**Speed:** 40 ft., climb 40 ft.

**STR**|**DEX**|**CON**|**INT**|**WIS**|**CHA**
---|---|---|---|---|---
25 (+7)|16 (+3)|24 (+7)|18 (+4)|20 (+5)|22 (+6)

**Saving Throws:** Str +13, Con +13, Wis +11, Cha +12
**Skills:** Athletics +13, Intimidation +12, Perception +11
**Damage Resistances:** Bludgeoning, Piercing, and Slashing from nonmagical attacks
**Condition Immunities:** Charmed, Frightened, Poisoned
**Senses:** Darkvision 120 ft., passive Perception 21
**Languages:** Common, Abyssal, Giant
**Challenge Rating:** 20 (25,000 XP)

**Legendary Resistance (3/Day).** If the Crowned Monstrosity fails a saving throw, it can choose to succeed instead.

**Magic Resistance.** The Crowned Monstrosity has advantage on saving throws against spells and other magical effects.

**Regeneration.** The Crowned Monstrosity regains 20 hit points at the start of its turn if it has at least 1 hit point remaining.

**Actions**

**Multiattack.** The Crowned Monstrosity makes three attacks: one with its Bite and two with its Claw.

**Bite.** *Melee Weapon Attack:* +13 to hit, reach 10 ft., one target. *Hit:* 22 (3d8 + 9) piercing damage.

**Claw.** *Melee Weapon Attack:* +13 to hit, reach 10 ft., one target. *Hit:* 20 (3d6 + 9) slashing damage.

**Crown Slam.** The Crowned Monstrosity slams its crown against the ground in a 30-foot cone. Each creature in that area must make a DC 20 Dexterity saving throw, taking 48 (8d10 + 7) bludgeoning damage on a failed save, or half as much damage on a successful one.

**Crown's Fury (Recharge 5-6).** The Crowned Monstrosity unleashes the corruptive power of the Crown of Thorns, causing spikes to erupt from the ground in a 60-foot radius centered on itself. Each creature in that area must make a DC 20 Strength saving throw, taking 66 (12d10) piercing damage and being restrained for 1 minute on a failed save, or half as much damage and not restrained on a successful one. A creature can repeat the saving throw at the end of each of its turns, ending the restrained effect on a success.

**Legendary Actions**

The Crowned Monstrosity can take 3 legendary actions, choosing from the options below. Only one legendary action option can be used at a time and only at the end of another creature's turn. The Crowned Monstrosity regains spent legendary actions at the start of its turn.

**Claw Attack.** The Crowned Monstrosity makes one Claw attack.

**Crown's Command.** The Crowned Monstrosity issues a telepathic command to one Ironclaw tribe member within 60 feet. The target must succeed

 on a DC 20 Wisdom saving throw or be charmed by the Crowned Monstrosity and compelled to carry out its orders on its next turn.

**Crown's Radiance.** The Crowned Monstrosity releases a burst of radiant energy in a 30-foot radius. Each creature of its choice in that area must make a DC 20 Constitution saving throw, taking 21 (6d6) radiant damage on a failed save, or half as much damage on a successful one.

**Phase Transition**

When Grimgar reaches 0 hit points, he undergoes a dramatic transformation. His body distorts and contorts, melding with the malevolent power of the Crown of Thorns. The monstrous crown fuses with his flesh, encasing him in a twisted armor of thorns and granting him enhanced abilities.

In his Phase 2 form as the Crowned Monstrosity, Grimgar gains additional hit points, increased attack damage, and access to devastating abilities. His appearance becomes grotesque, with elongated limbs, jagged thorns protruding from his body, and an eerie, otherworldly aura emanating from him. He becomes an even deadlier foe, capable of unleashing devastating attacks and manipulating the battlefield with his crown's corruptive power.

**Comment by jbhaywood** [comment]
Is that the exact text you pasted in Foundry? I'm seeing a table for the stats in the comment, but I think that's specific to GitHub markdown and wouldn't transfer to the statblock importer text box.

I'm asking because I copied the text from your comment and was able to import it without any error. If you could copy the text from the importer text box after you get the error and paste that here, that would be useful.
