### ISSUE TITLE
Doesn't like use of "feet" instead of "ft." in atacks

### ISSUE THREAD

**Issue by RebelMage** [jbhaywood/5e-statblock-importer#56]
I was testing out trying to import a statblock from Nightfell. Most of it worked correctly (expect a feature which didn't end with a period being merged with the feature after it, but that's an easy thing to fix while importing and isn't important), but I ran into an issue with the attack, which doesn't automatically parse the rolls. I compared it with the example, which did import correctly, and noticed the difference is that it has "feet" instead of "ft." in the description:

> Slam. Melee Weapon Attack: +3 to hit, reach 5 feet, one target. Hit: 4
(1d6+1) bludgeoning damage. On a hit, target creature must make
a DC 12 Wisdom Saving throw. On a failed save it loses 1 (1d2)
Soul Points.

After changing "feet" to "ft." it did import correctly. However, perhaps this is an issue that could be easily fixed?

(Did some mild digging around in the code, and it seems to be as simple as adding "feet|" to the regex for reach or range. I'm not sure which; I edited it in both just to make certain, and then it worked, and using ft. also still worked.)

**Comment by RebelMage** [comment]
I can't currently do that, and I'm not in any rush, so take your time!

**Comment by RebelMage** [comment]
Okay, ended up making a pull request, with a suggestion from a friend who likes regex. :P

**Comment by jbhaywood** [comment]
Fixed in version 1.69. Thanks for the pull request.
