### ISSUE TITLE
formal v11 support

### ISSUE THREAD

**Issue by MartijnSanders** [jbhaywood/5e-statblock-importer#59]
The module works in v11 (for me) but the module.json still has the verified compatibility version on v11. 
What's needed to be confident enough to up that to v11?

**Comment by jbhaywood** [comment]
Works for me. v1.7 should support Foundry 11.

**Comment by DiceAndEasy** [comment]
Would it be possible to update the module manifest so that the Foundry website and The Forge's Bazaar shows v11 as a supported version?

**Comment by jbhaywood** [comment]
The module config already has that information...
![image](https://github.com/jbhaywood/5e-statblock-importer/assets/5131886/15bd8168-b4c0-46bb-84e9-bac4937c7309)

But I updated the admin info (that's being deprecated), so maybe that'll fix it.

**Comment by DiceAndEasy** [comment]
That fixed the issue! Thanks!
