### ISSUE TITLE
Add proper support for damage resistance bypasses

### ISSUE THREAD

**Issue by arbron** [jbhaywood/5e-statblock-importer#60]
A few versions ago dnd5e added proper support for resistances like "bludgeoning, piercing, and slashing from nonmagical attacks", but the importer doesn't yet support them.

```javascript
"dr": {
  "value": ["bludgeoning", "piercing", "slashing"],
  "bypasses": ["magical"]
}
```

**Comment by MaxPat931** [comment]
Changing this line
https://github.com/jbhaywood/5e-statblock-importer/blob/ac12be9d5dd3ae071252ec7a6ebb33aadfb9163a/scripts/sbiParser.js#L619
To  
```js
const actorData = sbiUtils.assignToObject({}, `data.traits.dr.bypasses`, "mgc")
```

should do it
