### ISSUE TITLE
Errors importing in Adventures From Middle Earth books

### ISSUE THREAD

**Issue by pete284** [jbhaywood/5e-statblock-importer#7]
When copying and pasting from the PDF's of Adventures in Middle Earth books by Cubicle 7 some of the data doesn't import successfully. Armour Class, Hit Points, Hit Dice and damage with weapons. The data is in this format:

`Orc Soldier
Medium humanoid (Orc)
STR
13 (+1)
DEX
12 (+1)
CON
13 (+1)
INT
7 (-2)
WIS
11 (+0)
CHA
10 (+0)
Armour Class 13 (leather jerkin, optional +2 for shield)
Hit Points 15 (2d8+6)
Speed 30 ft
Skills Intimidation +2
Senses darkvision 60 ft., passive Perception 10
Languages Westron, Orkish
Challenge ½ (100 XP)
Aggressive. As a bonus action, the Orc Soldier can move
up to its speed toward a hostile creature that it can see.
Sunlight Sensitivity. While in sunlight, the Orc Soldier
has disadvantage on attack rolls, as well as on Wisdom
(Perception) checks that rely on sight.
Actions
Bent Sword. Melee Weapon Attack: +3 to hit, reach 5ft,
one target. Hit: 5 (1d8+1) slashing damage
Spear. Melee or Ranged Weapon Attack: +3 to hit, reach
5ft or range 20/60 ft., one target. Hit: 6 (1d6+3) piercing
damage or 4 (1d8+1) piercing damage when used as a
melee weapon.`

**Comment by jbhaywood** [comment]
I made some changes in v1.1.4 to better support this statblock, but it's still going to take a bit of manual editing before it'll work. The main thing is that it needs to be broken up into separate lines. The program just can't parse the statblock if it's one long block of text with no line breaks. The other thing is to make sure there's a period at the end of the sentences that end a feature or action, basically the things after the "Challenge" line. That's required for the program to know when one stops and a new one starts.

So take a look at this version and see how I edited it to make it formatted better...

```
Orc Soldier 
Medium humanoid (Orc) 
STR 13 (+1) DEX 12 (+1) CON 13 (+1) INT 7 (-2) WIS 11 (+0) CHA 10 (+0) 
Armour Class 13 (leather jerkin, optional +2 for shield) 
Hit Points 15 (2d8+6) 
Speed 30 ft 
Skills Intimidation +2 
Senses darkvision 60 ft., passive Perception 10 
Languages Westron, Orkish 
Challenge ½ (100 XP) 
Aggressive. As a bonus action, the Orc Soldier can move up to its speed toward a hostile creature that it can see. 
Sunlight Sensitivity. While in sunlight, the Orc Soldier has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight. 
Actions 
Bent Sword. Melee Weapon Attack: +3 to hit, reach 5ft, one target. Hit: 5 (1d8+1) slashing damage.
Spear. Melee or Ranged Weapon Attack: +3 to hit, reach 5ft or range 20/60 ft., one target. Hit: 6 (1d6+3) piercing damage or 4 (1d8+1) piercing damage when used as a melee weapon.
```

**Comment by pete284** [comment]
Oops githum messed up the paste. It is actually on multiple lines. I guessed it wouldn't be easy,and I'm pretty stoked it captures most of it as it saves me a ton of time. Thanks for your work on it and I'll check out latest version, 

`
Hill-Troll Chief
Large Giant (Troll-kind)  
STR  
 DEX  
 CON  
 INT  
 WIS  
 CHA  
19 (+4)  
 8 (-1)  
 19 (+4)  
 8 (-1)  
 10 (+0)  
 10 (+0)  
Armour Class 16 (bits of previous victims’ armour)  
Hit Points 95 (10d10+40)  
Speed 30 ft  
Saving Throws Strength +7, Constitution +7, Wisdom +3  
Skills Intimidation +3, Perception +3  
Senses darkvision 60 ft, passive Perception 11  
Languages Westron, Orkish  
Challenge 5 (1,800 XP)  
Hideous Toughness (Recharge after a short or long
rest). The Hill-troll Chief can endure enormous damage.
It may spend an action to spew forth various taunts and
imprecations along with a great deal of spittle. It then
gains a pool of 10 (3d6) temporary hit points that last till
the end of the fight if not removed by combat damage.
Actions  
Multiattack. The Hill-troll Chief makes two attacks: one
bite and one maul.  
Bite. Melee Weapon Attack: +7 to hit, reach 5 ft, one
target. Hit: 9 (2d4+4) slashing damage.    
Maul. Melee Weapon Attack: +7 to hit, reach 5 ft, one
target. Hit: 18 (4d6+4) bludgeoning damage.
`

**Comment by pete284** [comment]
Can confirm the latest version improves import for a/c hit points and hit dice. Thanks for the work on this.
