### ISSUE TITLE
Stablock Importer Cannot Read Properties.

### ISSUE THREAD

**Issue by ValdarDeValhero** [jbhaywood/5e-statblock-importer#71]
I use the Foundry Version 11 build  314 and when I try and install the module, I get the following error message.

![image](https://github.com/jbhaywood/5e-statblock-importer/assets/148683710/6ed1ff92-7e2f-4fbc-88ed-647b0145d9f6)

This is a crucial module for an extensive campaign, I am working on. Please help.

Thanks in advance for any assistance in solving this issue.

**Comment by jbhaywood** [comment]
I checked on the Foundry discord and someone suggested doing a full, clean reinstall. Some kind of "tokenizer issue". I don't know what that means exactly, but that file hasn't changed in years, outside of the version number being updated once in a while. So I don't know what else the problem might be. Let me know if a reinstall fixes it.

**Comment by ValdarDeValhero** [comment]
Thanks for checking - I have tried a few times over the last couple of weeks to reinstall, but the error message above comes up when I want to reinstall the module. I will have play with deactivating a few "token" related modules I have installed.

**Comment by jbhaywood** [comment]
Just to be clear, they meant a clean reinstall of Foundry itself, not just the module. Here was the response...

_Did the user do a full reinstall when updating to v11_
_This reads like a tokenizer type issue where they need a clean install_

And I assume they meant "tokenizer" as in data tokens, not map tokens. But I'm not totally sure.

**Comment by ValdarDeValhero** [comment]
Thanks for the clarification. Wont a complete reinstall affect the worlds I have a;ready created. I have spent a lot of time building it up - will be gutted if that was an unintended consequence?

**Comment by jbhaywood** [comment]
It _shouldn't_, but I can't guarantee it. It would be best to make a backup of the Foundry folder first. Or ask in the Discord about what to do. They're pretty helpful over there. Sorry I can't be of more help.

Also, make sure to update and try one more time. It seems to be working for others at this point.

**Comment by ValdarDeValhero** [comment]
Will do and thank you once again for your help.
