### ISSUE TITLE
Error Importing 

### ISSUE THREAD

**Issue by Dragonubis** [jbhaywood/5e-statblock-importer#73]
Winter Warden
Large elemental, unaligned
Armor Class 11
Hit Points 22 (5d6 + 3)
Speed 30 ft.
STR DEX CON INT WIS CHA
14 (+2) 10 (+0) 12 (+1) 6 (-2) 10 (+0) 6 (-2)
Saving Throws None
Skills None
Damage Resistances None
Damage Immunities None
Condition Immunities None
Senses Darkvision 60 ft., passive Perception 10
Languages None
Challenge 1/2 (100 XP)
Freezing Aura. The Winter Warden emanates an aura of cold within 10 feet. Creatures that start their turn in the aura must succeed on a DC 10 Constitution saving throw or take 5 (2d4) cold damage.
Slippery Terrain. The ground within a 5-foot radius of the Winter Warden is treated as difficult terrain. Additionally, creatures that start their turn within this area must make a successful DC 10 Dexterity saving throw or have their speed reduced to 0 until the start of their next turn.
Actions
Frozen Slam. Melee Attack: +3 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) bludgeoning damage plus 5 (2d4) cold damage. The target must succeed on a DC 10 Constitution saving throw or have its speed reduced by 10 feet until the start of its next turn.
Icy Blast. Ranged Attack: +3 to hit, range 30/60 ft., one target. Hit: 4 (1d6 + 1) cold damage. The target must succeed on a DC 10 Dexterity saving throw or have its speed reduced to 0 until the start of its next turn.

**Comment by jbhaywood** [comment]
Did you get an error message or was there something wrong with the actor sheet?

**Comment by MJgroomin** [comment]
I am also getting an error when trying to import stat blocks.

**Comment by jbhaywood** [comment]
Like I asked the last person, what’s the problem? I need more information before I can look into it. Give me the text you’re using and the problem you’re seeing.

**Comment by jbhaywood** [comment]
Without any other information I'm going to assume these are fixed in v1.81.8.

**Comment by Dragonubis** [comment]
I think The issue was with the text, everything else is working great!
