### ISSUE TITLE
5E STATBLOCK IMPORTER: An error has occurred

### ISSUE THREAD

**Issue by InsomniaKnight** [jbhaywood/5e-statblock-importer#74]
Harry Lime
Medium humanoid, neutral
Armor Class 18 (natural armor)
Hit Points 240 (20d12 + 120)
Speed 30 ft.
STR DEX CON INT WIS CHA
14 (+2) 10 (+0) 16 (+3) 8 (-1) 12 (+1) 10 (+0)
Saving Throws None
Skills Perception +5
Damage Resistances Piercing, Poison
Damage Immunities None
Condition Immunities Charmed, Frightened
Senses Passive Perception 15
Languages Common
Challenge 15 (13,000 XP)
Bumbling Presence. Harry's comical nature and bumbling presence often distract opponents, giving him advantage on Dexterity (Stealth) checks.
Trap Prone. Harry frequently falls victim to traps. Whenever Harry fails a saving throw against a trap, he takes additional damage equal to the trap's damage.
Legendary Resistance (3/Day). If Harry fails a saving throw, he can choose to succeed instead.
Actions
Multiattack. Harry makes two attacks with Backfire Dagger and one attack with Trap Shot.
Backfire Dagger. Harry clumsily throws a dagger at a target. +12 to hit, reach 20 ft., one target. Hit: 16 (2d10 + 5) piercing damage.
Trap Shot. Harry sets off a concealed trap, launching a projectile at a target. +12 to hit, range 60/180 ft., one target. On a hit, the target takes 27 (4d10 + 5) piercing damage. The target must make a DC 18 Constitution saving throw or be stunned until the end of Harry's next turn.
Silly Slipping Oil. Harry spills a vial of slippery oil on the ground, causing chaos and mayhem. Each creature in a 15-foot radius sphere centered on a point Harry chooses within 60 feet must make a DC 18 Dexterity saving throw. On a failed save, the creature takes 53 (15d6) bludgeoning damage and falls prone. On a successful save, the creature takes half as much damage and isn't prone.
Legendary Actions
Blundering Smash (Costs 2 Actions). Harry unleashes a wild swing with his weapon, hoping to hit his target. +12 to hit, reach 5 ft., one target. Hit: 38 (6d10 + 5) slashing damage. This attack also knocks the target prone.
Frantic Retreat (Costs 1 Action). Harry tries to get away from danger, using any means necessary. He can move up to his speed without provoking opportunity attacks.
Smoke Bomb (Costs 3 Actions). Harry tosses a smoke bomb at a point he can see within 30 feet. A 20-foot radius sphere of thick smoke appears at that point and lasts until the end of Harry's next turn. The area is heavily obscured, blocking vision and causing creatures inside it to be heavily obscured. The smoke dissipates if a strong wind blows through it. 
![Import error](https://github.com/jbhaywood/5e-statblock-importer/assets/85762853/1758cd6d-109d-46b5-a531-14a2796c9e98)

**Comment by jbhaywood** [comment]
Should be fixed in v1.81.8.
