### ISSUE TITLE
Lair actions not showing up on statblock

### ISSUE THREAD

**Issue by Uneasywheat** [jbhaywood/5e-statblock-importer#75]
I was doing some testing with this since I just got it and noticed I could not get lair actions to appear correctly on the statblock, I was trying to import an ancient void dragon from Kobold press tome of beasts 1 and the lair actions would not show up on the page, additionally the void slip from the dragon would not create a template, or a button for the players to click on for the saving throw.

**Comment by jbhaywood** [comment]
Can you paste the statblock text? I need to try it myself to see what’s up.

**Comment by Uneasywheat** [comment]
Dragon, Void
A dragon seemingly formed of the night sky has bright white stars
for eyes. Lesser stars twinkle in the firmament of the dragon’s body.
Children of the Stars. Void dragons drift through the
empty spaces beyond the boundaries of the mortal world,
wanderers between the stars. They are aloof, mingling only with
the otherworldly beings that live above and beyond the earth,
including the incarnate forms of the stars themselves. When lesser
creatures visit void dragons, the dragons themselves barely notice.
Witnesses to the Void. Void dragons are intensely
knowledgeable creatures, but they have seen too much, lingering
at the edge of the void itself. Gazing into the yawning nothing
outside has taken a toll. The void dragons carry a piece of that
nothing with them, and it slowly devours their being. They are all
unhinged, and their madness is contagious. It flows out of them
to break the minds of lesser beings when the dragons fly into a
rage and lash out.
Voracious Scholars. Despite their removed existence and
strange quirks, void dragons still hoard treasure. Gems that
glitter like the stars of their home are particularly prized. Their
crowning piece, however, is knowledge. Void dragons jealously
hoard scraps of forbidden and forgotten lore of any kind and
spend most of their time at home poring over these treasures.
Woe to any who disturbs this collection, for nothing ignites their
latent madness like a violation of their hoard.
ANCIENT VOID DRAGON
Gargantuan dragon, chaotic neutral
Armor Class 22 (natural armor)
Hit Points 448 (23d20 + 207)
Speed 40 ft., fly 80 ft. (hover)
STR DEX CON INT WIS CHA
28 (+9) 10 (+0) 29 (+9) 18 (+4) 15 (+2) 23 (+6)

Saving Throws Dex +7, Con +16, Wis +9, Cha +13
Skills Arcana +18, History +18, Perception +16, Persuasion +13,
Stealth +7
Damage Immunities cold
Condition Immunities charmed, frightened
Senses blindsight 60 ft. darkvision 120 ft. passive Perception 26
Languages Celestial, Common, Draconic, Infernal, Primordial,
Void Speech
Challenge 24 (62,000 XP)
Chill of the Void. Cold damage dealt by the void dragon
ignores resistance to cold damage, but not cold immunity.
Collapsing Star. When the void dragon is killed it explodes in a
swath of celestial destruction. Each creature and object within
1 mile of the dragon take 55 (10d10) bludgeoning damage, 55
(10d10) cold damage, and 55 (10d10) psychic damage. Each
damage type can be reduced by half with a successful DC 21
saving throw: Dexterity vs. bludgeoning, Constitution vs. cold,
and Wisdom vs. psychic. Additionally, a creature that fails two
or three of the saving throws is affected by a plane shift spell
and sent to a random plane. If it is sent to the plane it currently
occupies, it appears 5d100 miles away in a random direction.
Legendary Resistance (3/Day). If the dragon fails a saving
throw, it can choose to succeed instead.
Void Dweller. Void dragons dwell in the empty expanse
between the stars, and do not require air, food, drink, or sleep.
When flying between stars the void dragon magically glides on
solar winds, making the immense journey through the void in
an impossibly short time.
ACTIONS
Multiattack. The dragon can use its Aura of Madness. It then
makes three attacks: one with its bite and two with its claws.
Bite. Melee Weapon Attack: +16 to hit, reach 15 ft., one target.
Hit: 20 (2d10 + 9) piercing damage plus 14 (4d6) cold damage.
Claw. Melee Weapon Attack: +16 to hit, reach 10 ft., one target.
Hit: 16 (2d6 + 9) slashing damage plus 7 (2d6) cold damage.
Tail. Melee Weapon Attack: +16 to hit, reach 20 ft., one target.
Hit: 18 (2d8 + 9) bludgeoning damage.
Aura of Madness. Each creature of the dragon’s choice that is
within 120 feet of the dragon and aware of it must succeed
on a DC 22 Wisdom saving throw or become frightened for 1
minute. A creature repeats the saving throw at the end of each
of its turns, ending the effect on itself on a success. If a creature
fails the saving throw by 5 or more it is driven insane. An insane
creature is frightened permanently, and behaves as if affected
by confusion while it is frightened in this way. If a creature’s
saving throw is successful or the effect ends for it, the creature is
immune to the dragon’s Aura of Madness for the next 24 hours.
Breath Weapons (Recharge 5-6). The dragon uses one of the
following breath weapons.
Gravitic Breath. The dragon exhales a 90-foot cube of
powerful localized gravity, originating from the dragon.
Falling damage in the area increases to 1d10 per 10 feet
fallen. When a creature starts its turn within the area or

An ancient void dragon can be more deadly than CR 24
implies, thanks to the Collapsing Star ability. If characters
defeat one and kill it, they may be obliterated by 165 hp
cosmic blast damage—enough to kill characters outright,
if they take the full brunt. Characters have three chances
to reduce it with successful saving throws, and by the time
they’re strong enough to defeat an ancient void dragon,
some likely have resistance or immunity to one or more of
the damage types involved. So even if they’re completely
unprepared for the collapsing star effect, some of the
heroes will likely survive.
The key to facing an ancient void dragon is information.
NPCs and legends should encourage characters to research
this creature before battling one. Once they know the
terrible risk of killing one, they can prepare a plan for it—
and what might be a tragic “gotcha” deathtrap becomes a
challenging puzzle instead.
COLLAPSING STAR

Everett Eldridge - eeldridge10@gmail.com - 300279

139
TOME OF BEASTS • D

enters it for the first time in a turn, including when the
dragon creates the field, it must make a DC 24 Dexterity
saving throw. On a failure the creature is restrained. On
a success the creature’s speed is halved as long as it
remains in the field. A restrained creature repeats the
saving throw at the end of its turn. The field persists
until the dragon’s breath recharges, and it can’t use
gravitic breath twice consecutively.
Stellar Flare Breath. The dragon exhales star fire
in a 90-foot cone. Each creature in that area must
make a DC 24 Dexterity saving throw, taking 45
(13d6) fire damage and 45 (13d6) radiant damage
on a failed save, or half as much damage on a
successful one.
Teleport. The dragon magically teleports to any
open space within 100 feet.
REACTIONS
Void Twist. When the dragon is hit by a ranged
attack, it can create a small rift in space to increase
its AC by 7 against that attack. If the attack misses
because of this increase, the dragon can choose a
creature within 30 feet to become the new target for
that attack. Use the original attack roll to determine if
the attack hits the new target.
LEGENDARY ACTIONS
The dragon can take 3 legendary actions, choosing from
the options below. Only one legendary action option can
be used at a time and only at the end of another creature’s
turn. The dragon regains spent legendary actions at the start
of its turn.
Detect. The dragon makes a Wisdom (Perception) check.
Tail Attack. The dragon makes a tail attack.
Void Slip (Costs 2 Actions). The dragon twists the fabric
of space. Each creature within 15 feet of the dragon must
succeed on a DC 21 Dexterity saving throw or take 13 (2d6 + 6)
bludgeoning damage and be knocked prone. The dragon can
then teleport to an unoccupied space within 40 feet.
Void Cache (Costs 3 Actions). The dragon can magically reach
into its treasure hoard and retrieve one item. If the dragon is
holding an item, it can use this ability to deposit the item into
its hoard.

LAIR ACTIONS
On initiative count 20 (losing initiative ties), the dragon takes a
lair action to generate one of the following effects; the dragon
can’t use the same effect two rounds in a row:
• The dragon negates natural gravity within its lair (an area
affected by its gravitic breath is unaffected). Creatures drift
10 feet away from the ground over the course of a round and
are restrained. Flying creatures can move at half speed, unless
they have the (hover) tag or use magical flight, in which case
they move normally. This effect persists until initiative count
20 on the following round.
• The Void briefly overlaps the dragon’s lair in a 20-foot-radius
sphere of blackness punctuated by deep blue streaks and
pinpoints of light. The sphere is centered on a point the
dragon can see within 120 feet of the dragon. The area spreads

around corners, is heavily obscured, and contains no air
(creatures must hold their breath). Each creature in the sphere
when it appears must make a DC 15 Constitution saving
throw, taking 10 (3d6) cold damage on a failed save or half as
much on a successful one. Any creature that ends its turn in
the sphere takes 10 (3d6) cold damage. The sphere lasts until
the dragon uses this lair action again or until the dragon dies.
• The dragon rips the fabric of space, forcing two creatures it can
see within 120 feet of it to suddenly exist in the same place.
Space itself repels the creatures to their original positions.
Each creature takes 16 (3d10) force damage and is knocked
prone, or takes half as much damage and is not knocked prone
with a successful DC 15 Strength saving throw.

Sorry if this is not what you need, I'm doing this for my friend who's the GM and was looking for a way to create monsters quickly and I set this up for him, I would also like to state its possible I may not be copying and pasting things correctly but he tried it as well

**Comment by jbhaywood** [comment]
Btw, this whole section should be removed because it's not part of the statblock itself...

```
An ancient void dragon can be more deadly than CR 24
implies, thanks to the Collapsing Star ability. If characters
defeat one and kill it, they may be obliterated by 165 hp
cosmic blast damage—enough to kill characters outright,
if they take the full brunt. Characters have three chances
to reduce it with successful saving throws, and by the time
they’re strong enough to defeat an ancient void dragon,
some likely have resistance or immunity to one or more of
the damage types involved. So even if they’re completely
unprepared for the collapsing star effect, some of the
heroes will likely survive.
The key to facing an ancient void dragon is information.
NPCs and legends should encourage characters to research
this creature before battling one. Once they know the
terrible risk of killing one, they can prepare a plan for it—
and what might be a tragic “gotcha” deathtrap becomes a
challenging puzzle instead.
COLLAPSING STAR
```

That's part of the callout block on that page (I have the same book). It's separate from the statblock and will confuse the parser if it's included.

**Comment by Uneasywheat** [comment]
ok thank you for the feedback, I was confused because for instance on the dragon breath attacks it was adding those buttons and templates but I believe we've figured out why, and yes that did show up I just thought it was supposed to give him something to click on to show up in the log not just a block of text in the character sheet, thanks again!

**Comment by jbhaywood** [comment]
Yeah, the Lair Actions aren't broken out into their own items because there's nothing to track (there aren't a limited number of Lair Action) and there's no title for each, so I don't know what I'd put for the item name.
