### ISSUE TITLE
Bonus Action Spells importing issue

### ISSUE THREAD

**Issue by Briqckoleur** [jbhaywood/5e-statblock-importer#8]
Spells and Bonus actions require specific formatting and action to import properly.  I've found so far that the standard stat block does not import Spells unless they follow the Challenge rating in the stat block. Bonus actions must be in the same location, only they must have the action allocated to them after import and do not appear as actions. The initial statblock is as written with spaces removed, the spell book section for this statblock uses INT instead of CHA for the attribute and no spells are populated. The modified version maps the spells and the statistic properly, if the word "Innate" is not used, the spells do not import.

![Brigganock_Initial_Import](https://user-images.githubusercontent.com/67532338/134818556-6f794d9b-21d5-4aaf-9cea-4716d3d5a088.png)
[Brigganock_initial_statblock.txt](https://github.com/jbhaywood/5e-statblock-importer/files/7231914/Brigganock_initial_statblock.txt)

[Brigganock_ working_statblock_format.txt](https://github.com/jbhaywood/5e-statblock-importer/files/7231931/Brigganock_.working_statblock_format.txt)
)
![Brigganock_Working-ish_Import](https://user-images.githubusercontent.com/67532338/134818868-f8e1150f-8ac0-4f69-9aca-b156a6c766ec.png)

**Comment by jbhaywood** [comment]
Yep, I'm going to have to update the module to work with the new formatting in Wild Beyond the Witchlight. If you watched the D&D Celebration this weekend, Jeremy Crawford talked about how this is the new format going forward. I'll won't be able to get to it until Tuesday at the earliest.

**Comment by jbhaywood** [comment]
Fixed in v1.2.0.

**Comment by Briqckoleur** [comment]
Awesome! Thanks!
