### ISSUE TITLE
First Sense on a creature fails after initial import

### ISSUE THREAD

**Issue by MaxPat931** [jbhaywood/5e-statblock-importer#84]
The first sense on a creature is only imported the first time you use the importer, any subsequent imports after that always drop the first sense, requiring a refresh.

[SenseDrop.webm](https://github.com/jbhaywood/5e-statblock-importer/assets/86370342/8ac47777-9552-45e1-a0d7-daa55eff0955)

I havent been able to make progress on this one, but I suspect it has to do with setSenses?

https://github.com/jbhaywood/5e-statblock-importer/blob/87d629b5ad03f3137365cb2dfcd9d7573e694590/scripts/sbiParser.js#L423-L441

**Comment by jbhaywood** [comment]
This is definitely weird. I can't think of why it would be happening since it's not like we're saving any data from on run to another, unless it's accidental somewhere. But I think we're creating new objects every time.
