### ISSUE TITLE
MotM Spellcasting

### ISSUE THREAD

**Issue by MaxPat931** [jbhaywood/5e-statblock-importer#97]
Mordenkainen's Monsters of the Multiverse switches up spellcasting quite a bit causing it to not be parsed
The Spellcasting item is found in the Actions section, rather than features, and the description text moves some things around

```
Spellcasting. The warlock casts one of the following spells, using Charisma as the spellcasting ability (spell save DC 14):

At will: dancing lights, disguise self, mage armor (self only), mage hand, minor illusion, prestidigitation, speak with animals

1/day each: charm person, dimension door, hold monster
```
```
Spellcasting. The archdruid casts one of the following spells, using Wisdom as the spellcasting ability (spell save DC 17):

At will: beast sense, entangle, speak with animals

3/day each: animal messenger, dominate beast, faerie fire, tree stride

1/day each: commune with nature (as an action), mass cure wounds
```

Moving the spellcasting block out to the Features section and changing the name to Innate Spellcasting allows it to parse accurately, so perhaps some use of that logic can be used to capture this as an action. I'm not as familiar with this portion of the code, but I will take a look at it.

**Comment by Aioros** [comment]
This should be fixed with v1.90.1 and up (with an approach not too different from your PR). Let me know if it works for you.
